#! /bin/sh

BEGIN;

INSERT INTO config.profile(profile_id,profile_name,profile_desc,controller_name,agent) VALUES
(1,'default_Java','Default profile for Java','-','Java'),
(777777,'default_NodeJS','Default profile for Node JS','-','NodeJS'),
(888888,'default_DotNet','Default profile for Dot Net','-','Dot Net');

INSERT INTO config.entry_type(entry_type_id, entry_type_name, entry_type_detail) VALUES
(1,'HttpServletService','description'),
(2,'EntryForWebLogicJSP','description'),
(3,'ApacheJsperService','description'),
(4,'JerseyCall', 'description'),
(5,'GlassFishJersey', 'description'),
(6,'Generic', 'description'),
(7,'JMSCall', 'description'),
(8,'EntryForJBOSS', 'description'),
(9,'ErrorPageEntry','description'),
(10,'HessianCallOut','description'),
(11,'ATGServlet','description'),
(12,'TXExit','description');

INSERT INTO config.service_entry_points(entry_id,entry_desc,entry_fqm,entry_name,entry_type_id,custom_entry,module,agent) VALUES
(1,'Fully qualified name for the service method for HttpServlet Class','javax.servlet.http.HttpServlet.service(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V','HttpServlet.service', 1,false,'-','Java'),
(2,'fully qualified name for the doFilter method for weblogic','weblogic.servlet.internal.FilterChainImpl.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','FilterChainImpl.doFilter', 2,false,'-','Java'),
(3,' ','org.apache.jasper.runtime.HttpJspBase.service(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V','ApacheJsperService', 3,false,'-','Java'),
(4,' ','weblogic.servlet.jsp.JspBase.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','WebAppFilterChain.doFilter', 2,false,'-','Java'),
(5,' ','com.ibm.ws.webcontainer.servlet.ServletWrapper.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','ServletWrapper.service', 2,false,'-','Java'),
(6,' ','com.ibm.ws.webcontainer.servlet.ServletWrapper.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;Lcom/ibm/ws/webcontainer/webapp/WebAppServletInvocationEvent;)V','ServletWrapper.service-WebAppServletInvocationEvent', 2,false,'-','Java'),
(7,' ','org.apache.catalina.core.ApplicationFilterChain.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','ApplicationFilterChain.doFilter', 8,false,'-','Java'),
(8,' ','org.glassfish.jersey.servlet.ServletContainer.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','ServletContainer.service', 5,false,'-','Java'),
(9,' ','com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','WebAppFilterChain.doFilter', 2,false,'-','Java'),
(10,' ','weblogic.servlet.internal.RequestDispatcherImpl.forward(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','RequestDispatcherImpl.forward',9,false,'-','Java'),
(11,' ','com.caucho.hessian.server.HessianServlet.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','HessianServlet.service',10,false,'-','Java'),
(12,' ' ,'atg.servlet.pipeline.PipelineableServletImpl.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V', 'PipelineableServletImpl.service',11,false,'-','Java'),
(13,' ','atg.servlet.DynamoServlet.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','DynamoServlet.service',11,false,'-','Java'),
(14,' ','atg.servlet.sessionsaver.SessionSaverServlet.service(Latg/servlet/DynamoHttpServletRequest;Latg/servlet/DynamoHttpServletResponse;)V', 'SessionSaverServlet.service',11,false,'-','Java'),
(15,' ','atg.servlet.pipeline.HeadPipelineServlet.service(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V', 'HeadPipelineServlet.service',11,false,'-','Java'),
(16,' ','org.apache.activemq.ActiveMQMessageConsumer.dispatch(Lorg/apache/activemq/command/MessageDispatch;)V','ActiveMQMessageConsumer.dispatch',7,false,'-','Java'),
(17,' ','com.ibm.mq.jms.MQMessageConsumer$FacadeMessageListener.onMessage(Ljavax/jms/Message;)V','MQMessageConsumer$FacadeMessageListener.onMessage',7,false,'-','Java'),
(18,' ','System.Web.HttpRuntime.ProcessRequestNotificationPrivate','ProcessRequestNotificationPrivate',1,false,'System.Web.dll','Dot Net'),
(19,' ','System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper','ProcessRequestNotificationHelper',1,false,'System.Web.dll','Dot Net'),
(20,' ','System.Web.HttpRuntime.FinishPipelineRequest','FinishPipelineRequest',12,false,'System.Web.dll','Dot Net'),
(21,' ','System.Web.HttpRuntime.FinishRequest','FinishRequest',12,false,'System.Web.dll','Dot Net'),
(22,' ','org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','ServletHandler$CachedChain.doFilter',1,false,'-','Java');

INSERT INTO config.profile_service_entry_asso(prof_entry_id, profile_enable, entry_id, profile_id) VALUES
(1, true, 1, 1),
(2, true, 2, 1),
(3, true, 3, 1),
(4, true, 4, 1),
(5, true, 5, 1),
(6, true, 6, 1),
(7, true, 7, 1),
(8, false, 8, 1),
(9, true, 9, 1),
(10, true, 10, 1),
(11, true, 11, 1),
(12, false, 12, 1),
(13, false, 13, 1),
(14, false, 14, 1),
(15, false, 15, 1),
(16, false, 16, 1),
(17, false, 17, 1),
(18, true, 18, 888888),
(19, true, 19, 888888),
(20, true, 20, 888888),
(21, true, 21, 888888),
(22, true, 22, 1);


INSERT INTO config.keywords_meta_data(kmd_id,key_type,key_type_id) VALUES
(1,'char','0'),
(2,'integer','1'),
(3,'double','2'),
(4,'long long','3'),
(5,'string','4'),
(6,'file','5');

INSERT INTO config.keywords(key_id,key_name,key_min,key_max,kmd_id,key_def_value,type) VALUES
(1,'bciInstrSessionPct','0','100','5','0','normal'),
(2,'logLevelOneFpMethod','0','1','1','0','normal'),
(3,'enableBciDebug','0','6','1','1','normal'),
(4,'enableBciError','1','100','5','1','normal'),
(5,'doNotDiscardFlowPaths','0','1','2','0','pre-custom'),
(6,'ASSampleInterval','0','5000','4','500','normal'),
(7,'ASThresholdMatchCount','1','100','4','5','normal'),
(8,'ASReportInterval','0','900000','4','0','normal'),
(9,'instrProfile','','','5','','normal'),
(10,'ASDepthFilter','0','100','2','20','normal'),
(11,'ASTraceLevel','0','20','2','1','pre-custom'),
(12,'enableNDSession','0','1024','5','0','normal'),
(13,'enableCpuTime','0','1024','1','0','normal'),
(14,'enableForcedFPChain','0','3','2','1','normal'),
(15,'InstrTraceLevel','0','11','2','0','normal'),
(16,'instrExceptions','0','512','5','1%201%200%2020','normal'),
(17,'correlationIDHeader','0','1024','5','-','normal'),
(18,'ASStackComparingDepth','0','1000','4','10','normal'),
(19,'putDelayInMethod','0','10240','5','0','normal'),
(20,'enableBackendMonitor','0','1','2','1','normal'),
(21,'NDEntryPointsFile','','','5','true','normal'),
(22,'ndMethodMonTraceLevel','0','10','2','0','normal'),
(23,'generateExceptionInMethod','0','10240','5','0','normal'),
(24,'captureHTTPReqFullFp','1','10485760','5','2','normal'),
(25,'NDHTTPReqHdrCfgListFullFp','1','1024','6','NA','normal'),
(26,'captureHTTPRespFullFp','1','1048576','5','1','normal'),
(27,'enableBTMonitor','0','1','2','1','normal'),
(28,'BTRuleConfig','NA','NA','5','global','normal'),
(29,'ndMethodMonFile','','','5','false','normal'),
(30,'BTErrorRules','','','5','false','normal'),
(32,'enableJVMThreadMonitor','0','2048','5','0','normal'),
(33,'captureCustomData','','','5','false','normal'),
(34,'ASPositiveThreadFilters','2','1048576','5','NA','normal'),
(35,'ASNegativeThreadFilter','2','1048576','5','NDControlConnection','normal'),
(36,'maxStackSizeDiff','0','1000','4','20','normal'),
(37,'ASMethodHotspots','0','1','1','-1','normal'),
(38,'enableExceptionInSeqBlob','0','1','2','0','pre-custom'),
(39,'captureErrorLogs','0','2','2','0','normal'),
(40,'maxExceptionMessageLength','0','10000','2','50','pre-custom'), 
(41,'maxResourceDetailMapSize','0','1000000','2','500000','pre-custom'),
(42,'HTTPStatsCondCfg','1','1024','5','false','normal'),
(43,'enableExceptionsWithSourceAndVars','0','248','2','0','normal'),
(44,'enableSourceCodeFilters','1','1024','5','false','normal'),
(45,'ndExceptionMonFile','','','5','false','normal'),
(46,'maxQueryDetailMapSize','0','10000000','1','10000','pre-custom'),
(47,'formatIPResourceURL','0','512','5','1','normal'),
(48,'enableIPResourceURL','0','1','2','0','normal'),
(49,'dumpDefaultCassandraQuery','0','1','2','0','normal'),
(50,'enableTransformThreadSubClass','0','1','2','1','normal'),
(51,'captureDocumentforMongo','0','1','2','0','normal'),
(52,'enableErrorRedirectionPage','0','1','2','0','normal'),
(53,'enableMethodBreakDownTime','0','1024','5','0','normal'),
(54,'NDHTTPRepHdrCfgListFullFp','1','1024','6','NA','pre-custom'),
(55,'NDHTTPRepHdrCfgListL1Fp','1','1024','6','NA','pre-custom'),
(56,'ndHttpHdrCaptureFileList','1','1024','6','NA','pre-custom'),
(57,'ASReportDumpMode','0','3','1','1','normal'),
(58,'ASStackCompareOption','1','2','4','1','pre-custom'),
(59,'ASDataBufferMinCount','2','1024','4','16','pre-custom'),
(60,'ASEnableFPSummaryReport','0','2','2','0','normal'),
(61,'ASResumeDataBuffFreePct','1','100','4','25','pre-custom'),
(62,'ndMonitorInterval','0','2147483647','2','0','normal'),
(63,'captureExceptionTraceLevel','0','10','2','0','normal'),
(64,'enableThreadCallout','0','10240','5','1','normal'),
(65,'enableThreadMonTraceLevel','0','10','2','0','normal'),
(66,'enableBTMonitorTrace','0','6','2','0','normal'),
(67,'maxBTCount','1','5000','2','256','normal'),
(68,'maxIPCount','1','1000','2','32','normal'),
(69,'enableFPTrace','0','3','2','0','normal'),
(70,'AgentTraceLevel','0','4','2','0','pre-custom'),
(71,'captureHttpSessionTraceLevel','0','3','1','1','normal'),
(72,'ndExceptionThrowingClassFilter','1','1024','6','NA','normal'),
(73,'captureMethodForAllFP','0','1','2','0','normal'),
(74,'ndBackendNamingRulesFile','1','1024','6','true','normal'),
(75,'ndExceptionFilterList','0','10240','6','NA','pre-custom'),
(76,'enableBackendMonTrace','0','6','2','0','pre-custom'),
(77,'enableForcedFPChain','0','3','2','1','pre-custom'),
(78,'maxCharInSeqBlob','0','1024000000','5','10','pre-custom'),
(79,'bciMaxNonServiceMethodsPerFP','0','2147483647','5','50000','pre-custom'),
(80,'bciDataBufferMaxCount','1','30000','4','512','pre-custom'),
(81,'bciDataBufferMaxSize','128','65536','4','32768','pre-custom'),
(82,'ASDataBufferSize','1','2147483647','4','64000','pre-custom'),
(83,'ASDataBufferMaxCount','2','1024','4','256','pre-custom'),
(84,'NVCookie','2','1048576','5','CavNVC','pre-custom'),
(85,'NDAppLogFile','1','1024','6','NA','pre-custom'),
(86,'ndBackendMonFile','1','1024','6','NA','pre-custom'),
(87,'generateExceptionConfFile','1','1024','6','NA','pre-custom'),
(88,'cavNVURLFile','1','1024','6','NA','pre-custom'),
(89,'NDInterfaceFile','1','1024','6','NA','pre-custom'),
(90,'genNewMonRecord','0','1','2','1','pre-custom'),
(91,'BTAggDataArraySize','50','5000','2','50','pre-custom'),
(92,'AppLogTraceLevel','0','6','2','0','pre-custom'),
(93,'ControlThreadTraceLevel','0','4','2','0','pre-custom'),
(94,'BCITraceMaxSize','1024','1073741824','4','10485760','pre-custom'),
(95,'ASEnableHotspotRecord','0','2','2','2','pre-custom'),
(96,'eventLoopMonitor','0','1','2','1','normal'),
(97,'gcProfiler','0','1','2','1','normal'),
(98,'nodejsCpuProfilingTime','10','120','2','10','normal'),
(99,'nodeAsyncEventMonitor','0','1','2','0','normal'),
(100,'nodeServerMonitor','0','1','2','0','normal'),
(101,'captureHttpTraceLevel','0','6','2','0','pre-custom'),
(102,'excludeMethodOnRespTime','0','90000','2','0','normal'),
(103,'dumpOnlyMethodExitInFP','0','1','2','0','normal'),
(104, 'methodResponseTimeFilter', '0', '360000', '5', '0%201%2020', 'normal'),
(105,'NDAsyncRuleConfig','1','1024','6','false','normal'),
(106,'enableHSLongStack','0','1024','5','0%5%Immediate,TickObject,Timeout,TIMERWRAP','normal'),
(107,'correlateEventCallback','0','512','5','0','normal');


INSERT INTO config.backend_type(backend_type_id,backend_type_detail,backend_type_name,backend_type_name_entrypointsfile,backend_type_name_rulefile,agent) VALUES
(1,'HTTP Backend','HTTP','HttpCallout','HTTP','Java'),
(2,'Web Services Backend','Web Services','HttpCallout','WS','Java'),
(3,'JDBC Backend','JDBC','oracleDB','JDBC','Java'),
(4,'Coherence Backend','Coherence','HttpCallout','None','Java'),
(5,'RMI Backend','RMI','HttpCallout','RMI','Java'),
(6,'Mem Cache Backend','Mem Cache','HttpCallout','None','Java'),
(7,'Cloudant Backend','Cloudant','HttpCallout','None','Java'),
(8,'Hadoop Backend','Hadoop','HttpCallout','HBASE','Java'),
(9,'Custom  Backend','Custom','CustomCallout:','None','Java'),
(10,'Redis Backend','Redis','redis','REDIS','Java'),
(11,'Mongo Backend','Mongo','mongodb','MONGO','Java'),
(12,'Cassandra Backend','Cassandra','cassandra','None','Java'),
(13,'Custom Log Backend','Custom Log','CustomLog','None','Java'),
(14,'Custom Error Log Backend','Custom Error Log','CustomErrorlog','None','Java'),
(15,'Thread Backend','Thread','Thread','None','Java'),
(16,'HTTP Backend For Dot Net','HTTP','HTTP_CALLOUT','HTTP','Dot Net'),
(17,'SQL Backend For Dot Net','SQL','SQL_CALLOUT','SQL','Dot Net'),
(18,'Async Call For Dot Net','Async_Call','ASYNC_CALL','ASYNC_CALL','Dot Net'),
(19,'Cloudant NoSQL Backend','Cloudant NoSQL','cloudantEntry','CloudantNoSql','Java'),
(20,'Big Table Backend','Big Table','bigTable','None','Java'),
(21,'Microsoft SQL Backend','Microsoft SQL','microsoftDB','None','Java');

    INSERT INTO config.backend_points(end_point_id,end_point_desc,end_point_fqm,end_point_name,backend_type_id,custom_entry,module,agent) VALUES
(1,'HTTP end point','org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Lorg/apache/commons/httpclient/HttpMethod;)V','Apace HTTP Client',1,false,'-','Java'),
(2,'HTTP end point','com.endeca.navigation.HttpENEConnection.query(Lcom/endeca/navigation/ENEQuery;)Lcom/endeca/navigation/ENEQueryResults;','Endeca',1,false,'-','Java'),
(3,'HTTP end point','org.apache.http.impl.client.AbstractHttpClient.execute(Lorg/apache/http/HttpHost;Lorg/apache/http/HttpRequest;Lorg/apache/http/protocol/HttpContext;)Lorg/apache/http/HttpResponse;','Apache AbstractHttpClient',1,false,'-','Java'),
(4,'HTTP end point','org.apache.http.impl.client.DefaultRequestDirector.execute(Lorg/apache/http/HttpHost;Lorg/apache/http/HttpRequest;Lorg/apache/http/protocol/HttpContext;)Lorg/apache/http/HttpResponse;','Apache Default HTTP Client',1,false,'-','Java'),
(5,'HTTP end point','org.apache.wink.client.internal.handlers.HttpURLConnectionHandler.processRequest(Lorg/apache/wink/client/ClientRequest;Lorg/apache/wink/client/handlers/HandlerContext;)Ljava/net/HttpURLConnection;','Apache Wink Client',1,false,'-','Java'),
(6,'HTTP end point','com.worklight.adapters.http.HTTPConnectionManager.execute(Lorg/apache/http/HttpRequest;Lorg/apache/http/protocol/HttpContext;)Lorg/apache/http/HttpResponse;','MFP Worklight HTTP Client',1,false,'-','Java'),
(7,'HTTP end point','org.springframework.web.client.RestTemplate.doExecute(Ljava/net/URI;Lorg/springframework/http/HttpMethod;Lorg/springframework/web/client/RequestCallback;Lorg/springframework/web/client/ResponseExtractor;)Ljava/lang/Object;','Spring REST Template Client',1,false,'-','Java'),
(8,'HTTP end point','org.springframework.web.client.RestTemplate\$HttpEntityRequestCallback.doWithRequest(Lorg/springframework/http/client/ClientHttpRequest;)V','Spring add Header in REST Callback Template Client',1,false,'-','Java'),
(9,'HTTP end point','org.springframework.http.client.support.HttpAccessor.createRequest(Ljava/net/URI;Lorg/springframework/http/HttpMethod;)Lorg/springframework/http/client/ClientHttpRequest;','Spring add Header in REST Client Template Client',1,false,'-','Java'),
(10,'HTTP end point','org.apache.http.impl.client.InternalHttpClient.doExecute(Lorg/apache/http/HttpHost;Lorg/apache/http/HttpRequest;Lorg/apache/http/protocol/HttpContext;)Lorg/apache/http/client/methods/CloseableHttpResponse;','Apache Internal HTTP Client',1,false,'-','Java'),
(11,'WS end point','org.glassfish.jersey.client.JerseyInvocation.invoke()Ljavax/ws/rs/core/Response;','Jersey Webservice Client',2,false,'-','Java'),
(12,'WS end point','com.sun.xml.messaging.saaj.client.p2p.HttpSOAPConnection.post(Ljavax/xml/soap/SOAPMessage;Ljava/net/URL;)Ljavax/xml/soap/SOAPMessage;','HTTP SOAP connection',2,false,'-','Java'),
(13,'WS end point','com.sun.xml.ws.transport.http.client.HttpClientTransport.<init>(Lcom/sun/xml/ws/api/message/Packet;Ljava/util/Map;)V','HTTP Client Transport',2,false,'-','Java'),
(14,'WS end point','com.sun.xml.ws.transport.http.client.HttpTransportPipe.processRequest(Lcom/sun/xml/ws/api/message/Packet;)Lcom/sun/xml/ws/api/pipe/NextAction;','HTTP Transport Pipe',2,false,'-','Java'),
(15,'WS end point','org.apache.cxf.jaxws.JaxWsClientProxy.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;','Apache cxf Webservice',2,false,'-','Java'),
(16,'RMI end point','java.rmi.Naming.lookup(Ljava/lang/String;)Ljava/rmi/Remote;','RMI Lookup Calls',5,false,'-','Java'),
(17,'RMI end point','java.rmi.Naming\$ParsedNamingURL.<init>(Ljava/lang/String;ILjava/lang/String;)','RMI Request',5,false,'-','Java'),
(19,'JDBC end point','oracle.jdbc.driver.OraclePreparedStatementWrapper','oracleDB',3,false,'-','Java'),
(20,'HADOOP end point','org.springframework.data.hadoop.hbase.HbaseTemplate.execute(Ljava/lang/String;Lorg/springframework/data/hadoop/hbase/TableCallback;)Ljava/lang/Object;','Spring HBASE',8,false,'-','Java'),
(21,'COHERENCE end point','com.tangosol.net.cache.CachingMap.get(Ljava/lang/Object;)Ljava/lang/Object;','Coherence get',4,false,'-','Java'),
(22,'COHERENCE end point','com.tangosol.net.cache.CachingMap.getAll(Ljava/util/Collection;)Ljava/util/Map;','Coherence getAll',4,false,'-','Java'),
(23,'COHERENCE end point','com.tangosol.net.cache.CachingMap.put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;','Coherence put',4,false,'-','Java'),
(24,'COHERENCE end point','com.tangosol.net.cache.CachingMap.put(Ljava/lang/Object;Ljava/lang/Object;ZJ)Ljava/lang/Object;','Coherence put',4,false,'-','Java'),
(25,'COHERENCE end point','com.tangosol.net.cache.CachingMap.putAll(Ljava/util/Map;)V','Coherence putAll',4,false,'-','Java'),
(26,'COHERENCE end point','com.tangosol.net.cache.CachingMap.remove(Ljava/lang/Object;)Ljava/lang/Object;','Coherence remove',4,false,'-','Java'),
(27,'MEM CACHE end point','net.rubyeye.xmemcached.XMemcachedClient.add0(Ljava/lang/String;ILjava/lang/Object;Lnet/rubyeye/xmemcached/transcoders/Transcoder;J)Z','Mem Cache add',6,false,'-','Java'),
(28,'MEM CACHE end point','net.rubyeye.xmemcached.XMemcachedClient.getMulti0(Ljava/util/Collection;JLnet/rubyeye/xmemcached/command/CommandType;Lnet/rubyeye/xmemcached/transcoders/Transcoder;)Ljava/util/Map;','MEM CACHE getMulti',6,false,'-','Java'),
(29,'MEM CACHE end point','net.rubyeye.xmemcached.XMemcachedClient.get0(Ljava/lang/String;JLnet/rubyeye/xmemcached/command/CommandType;Lnet/rubyeye/xmemcached/transcoders/Transcoder;)Ljava/lang/Object;','Mem Cache get',6,false,'-','Java'),
(30,'MEM CACHE end point','net.rubyeye.xmemcached.XMemcachedClient.delete0(Ljava/lang/String;IJZJ)Z','Mem Cache delete',6,false,'-','Java'),
(31,'MEM CACHE end point','net.rubyeye.xmemcached.XMemcachedClient.replace(Ljava/lang/String;ILjava/lang/Object;Lnet/rubyeye/xmemcached/transcoders/Transcoder;J)Z','Mem Cache replace',6,false,'-','Java'),
(32,'CLOUDANT end point','org.lightcouch.CouchDbClientBase.executeRequest(Lorg/apache/http/client/methods/HttpRequestBase;)Lorg/apache/http/HttpResponse;','Cloudant executeRequest',7,false,'-','Java'),
(33,'HTTP end point','javax.naming.ldap.InitialLdapContext.<init>(Ljava/util/Hashtable;[Ljavax/naming/ldap/Control;)V','Initial LDAP Context',1,false,'-','Java'),
(34,'HTTP end point','weblogic.servlet.internal.ServletResponseImpl.writeHeaders()V','Weblogic Servlet Response headers',1,false,'-','Java'),
(35,'HTTP end point','com.hazelcast.client.spi.ClientProxy.invoke(Lcom/hazelcast/client/impl/protocol/ClientMessage;)Ljava/lang/Object;','Hazelcast client proxy',1,false,'-','Java'),
(36,'JDBC end point','com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement','Prepared Statement : ibmDB',3,false,'-','Java'),
(37,'JDBC end point','com.ibm.ws.rsadapter.jdbc.WSJdbcStatement','Statement : ibmDB',3,false,'-','Java'),
(38,'JDBC end point','com.mysql.jdbc.PreparedStatement','Prepared Statement : mysqlDB',3,false,'-','Java'),
(39,'JDBC end point','org.apache.openjpa.kernel.DelegatingQuery.execute()Ljava/lang/Object;','execute()Ljava/lang/Object : openJPADB',3,false,'-','Java'),
(40,'JDBC end point','org.apache.openjpa.kernel.DelegatingQuery.execute(Ljava/util/Map;)Ljava/lang/Object;','execute(Ljava/util/Map;)Ljava/lang/Object : openJPADB',3,false,'-','Java'),
(41,'JDBC end point','org.apache.openjpa.kernel.DelegatingQuery.execute([Ljava/lang/Object;)Ljava/lang/Object;','execute([Ljava/lang/Object;)Ljava/lang/Object : openJPADB',3,false,'-','Java'),
(42,'REDIS end point','redis.clients.jedis.Jedis','Jedis : redisDB',10,false,'-','Java'),
(43,'REDIS end point','redis.clients.jedis.BinaryJedis','Binary Jedis : redisDB',10,false,'-','Java'),
(44,'MONGO end point','com.mongodb.DBCollection','DB Collection : mongoDB',11,false,'-','Java'),
(45,'MONGO end point','com.mongodb.DB',' DB : mongoDB',11,false,'-','Java'),
(46,'CASSANDRA end point','com.datastax.driver.core.SessionManager',' SessionManager : cassandraDB',12,false,'-','Java'),
(47,'CASSANDRA end point','com.datastax.driver.core.RequestHandler',' RequestHandler : cassandraDB',12,false,'-','Java'),
(48,'CUSTOM LOG end point','atg.nucleus.logging.LogEvent.<init>(Ljava/lang/String;Ljava/lang/Throwable;)V','LogEvent.<init>(String,Throwable)',13,false,'-','Java'),
(49,'CUSTOM LOG end point','atg.nucleus.logging.LogEvent.<init>(Ljava/lang/String;Ljava/lang/String;)V','LogEvent.<init>(String,String)',13,false,'-','Java'),
(50,'CUSTOM LOG end point','atg.nucleus.logging.LogEvent.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)V','LogEvent.<init>(String,String,Throwable)',13,false,'-','Java'),
(51,'CUSTOM LOG end point','atg.nucleus.logging.LogEvent.<init>(Ljava/lang/String;)V','LogEvent.<init>(String)',13,false,'-','Java'),
(52,'CUSTOM ERROR LOG end point','atg.nucleus.logging.LogEvent.<init>(Ljava/lang/String;Ljava/lang/Throwable;)V','LogEvent.<init>(String,Throwable)',14,false,'-','Java'),
(53,'CUSTOM ERROR LOG end point','atg.nucleus.logging.LogEvent.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)V','LogEvent.<init>(String,String,Throwable)',14,false,'-','Java'),
(54,'CUSTOM ERROR LOG end point','ch.qos.logback.classic.spi.LoggingEvent.<init>(Ljava/lang/String;Lch/qos/logback/classic/Logger;Lch/qos/logback/classic/Level;Ljava/lang/String;Ljava/lang/Throwable;[Ljava/lang/Object;)V','LoggingEvent.<init>(String,Logger,Level,String,Throwable,Object)',14,false,'-','Java'),
(55,'THREAD end point','java.lang.Thread.start()V','start()',15,false,'-','Java'),
(56,'THREAD end point','java.lang.Thread.run()V','run()',15,false,'-','Java'),
(57,'THREAD end point','java.util.concurrent.ThreadPoolExecutor.execute(Ljava/lang/Runnable;)V','execute(Runnable)',15,false,'-','Java'),
(58,'THREAD end point', 'java.util.concurrent.ThreadPoolExecutor.beforeExecute(Ljava/lang/Thread;Ljava/lang/Runnable;)V','beforeExecute(Thread,Runnable)',15, false,'-','Java'), 
(59,'THREAD end point','java.util.concurrent.ThreadPoolExecutor.afterExecute(Ljava/lang/Runnable;Ljava/lang/Throwable;)V','afterExecute(Throwable)',15,false,'-','Java'),
(60,'THREAD end point','java.util.concurrent.ForkJoinPool.addSubmission(Ljava/util/concurrent/ForkJoinTask;)V','addSubmission(ForkJoinTask)',15,false,'-','Java'),
(61,'THREAD end point','java.util.concurrent.ForkJoinTask.doExec()V','doExec()V',15,false,'-','Java'),
(62,'THREAD end point','java.util.concurrent.ForkJoinPool.externalPush(Ljava/util/concurrent/ForkJoinTask;)V','externalPush(ForkJoinTask)',15,false,'-','Java'),
(63,'THREAD end point','java.util.concurrent.ForkJoinTask.doExec()I','doExec()I',15,false,'-','Java'),
(64,'THREAD end point','com.tibco.pe.core.JobDispatcher.schedule(Lcom/tibco/pe/core/Job;)V','schedule(Job)',15,false,'-','Java'),
(65,'THREAD end point','com.tibco.pe.core.JobDispatcher$JobCourier.a(Lcom/tibco/pe/core/Job;)Z','a(Job)',15,false,'-','Java'),
(66,'WS end point','com.sun.xml.ws.transport.http.client.HttpTransportPipe.writeSOAPAction(Ljava/util/Map;Ljava/lang/String;Lcom/sun/xml/ws/api/message/Packet;)V','writeSOAPAction(Map,String,Packet)(i.e Ljava/lang/String;Lcom/sun/xml/ws/api/message/Packet;)',2,false,'-','Java'),
(67,'WS end point','com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest(Lcom/sun/xml/internal/ws/api/message/Packet;)Lcom/sun/xml/internal/ws/api/pipe/NextAction;','writeSOAPAction(Packet)',2,false,'-','Java'),
(68,'WS end point','com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.writeSOAPAction(Ljava/util/Map;Ljava/lang/String;)V','writeSOAPAction(Map,String)',2,false,'-','Java'),
(69,'WS end point','com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.writeSOAPAction(Ljava/util/Map;Ljava/lang/String;Lcom/sun/xml/internal/ws/api/message/Packet;)V','writeSOAPAction(Map,String,Packet)(i.e Lcom/sun/xml/internal/ws/api/message/Packet;)',2,false,'-','Java'),
(70,'HTTP end point for dot net','System.Net.HttpWebRequest.GetResponse','HttpWebRequest.GetResponse',16,false,'System.dll','Dot Net'),
(71,'HTTP end point for dot net','System.Net.HttpWebRequest.BeginGetRequestStream', 'HttpWebRequest.BeginGetRequestStream' ,16, false,'System.dll','Dot Net'),
(72,'HTTP end point for dot net','System.Net.HttpWebRequest.BeginGetResponse','HttpWebRequest.BeginGetResponse',16,false,'System.dll','Dot Net'),
(73,'HTTP end point for dot net','System.Net.HttpWebRequest.EndGetResponse','HttpWebRequest.EndGetResponse',16,false,'System.dll','Dot Net'),
(74,'HTTP end point for dot net','System.Net.HttpWebRequest.GetRequestStream','HttpWebRequest.GetRequestStream',16,false,'System.dll','Dot Net'),
(75,'SQL call for dot net','System.Data.SqlClient.SqlCommand.ExecuteReader','SqlCommand.ExecuteReader',17,false,'System.Data.dll','Dot Net'),
(76,'HTTP end point for dot net','System.Data.SqlClient.SqlCommand.ExecuteScalar', 'SqlCommand.ExecuteScalar' ,17, false,'System.Data.dll','Dot Net'),
(77,'SQL call for dot net','System.Data.SqlClient.SqlCommand.ExecuteNonQuery','SqlCommand.ExecuteNonQuery',17,false,'System.Data.dll','Dot Net'),
(78,'SQL call for dot net','System.Data.SqlClient.SqlCommand.ExecuteDbDataReader','SqlCommand.ExecuteDbDataReader',17,false,'System.Data.dll','Dot Net'),
(79,'SQL call for dot net','System.Data.SqlClient.SqlCommand.FinishExecuteReader','SqlCommand.FinishExecuteReader',17,false,'System.Data.dll','Dot Net'),
(80,'SQL call for dot net','System.Data.SqlClient.SqlCommand.RunExecuteReader','SqlCommand.RunExecuteReader',17,false,'System.Data.dll','Dot Net'),
(81,'SQL call for dot net','System.Data.SqlClient.SqlCommand.RunExecuteReaderTds','SqlCommand.RunExecuteReaderTds',17,false,'System.Data.dll','Dot Net'),
(82,'SQL call for dot net','System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery','SqlCommand.InternalExecuteNonQuery',17,false,'System.Data.dll','Dot Net'),
(83,'ASYNC call for dot net','System.Web.HttpApplication.ExecuteStep','HttpApplication.ExecuteStep',18,false,'System.Web.dll','Dot Net'),
(84,'ASYNC call for dot net','System.Runtime.IOThreadScheduler.ScheduleCallbackLowPriNoFlow','IOThreadScheduler.ScheduleCallbackLowPriNoFlow',18,false,'System.ServiceModel.Internals.dll','Dot Net'),
(85,'ASYNC call for dot net', 'System.ServiceModel.Activation.HostedHttpRequestAsyncResult.OnBeginRequest','HostedHttpRequestAsyncResult.OnBeginRequest',18, false,'System.ServiceModel.Activation.dll','Dot Net'),
(86,'CLOUDANT NoSQL end point','com.cloudant.client.org.lightcouch.CouchDatabaseBase.find(Ljava/lang/String;)Ljava/io/InputStream;','Cloudant NoSQL find',19,false,'-','Java'),
(87,'CLOUDANT NoSQL end point','com.cloudant.client.org.lightcouch.CouchDatabaseBase.save(Ljava/lang/Object;)Lcom/cloudant/client/org/lightcouch/Response;','Cloudant NoSQL save',19,false,'-','Java'),
(88,'CLOUDANT NoSQL end point','com.cloudant.client.org.lightcouch.CouchDatabaseBase.post(Ljava/lang/Object;)Lcom/cloudant/client/org/lightcouch/Response;','Cloudant NoSQL post',19,false,'-','Java'),
(89,'CLOUDANT NoSQL end point','com.cloudant.client.org.lightcouch.CouchDatabaseBase.update(Ljava/lang/Object;)Lcom/cloudant/client/org/lightcouch/Response;','Cloudant NoSQL update',19,false,'-','Java'),
(90,'CLOUDANT NoSQL end point','com.cloudant.client.org.lightcouch.CouchDatabaseBase.remove(Ljava/lang/Object;)Lcom/cloudant/client/org/lightcouch/Response;','Cloudant NoSQL remove',19,false,'-','Java'),
(91,'WS end point','com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection.post(Ljavax/xml/soap/SOAPMessage;Ljava/net/URL;)Ljavax/xml/soap/SOAPMessag e;','post(SOAP,URL)',2,false,'-','Java'),
(92,'CASSANDRA end point','com.datastax.driver.core.AbstractSession',' AbstractSession : cassandraDB',12,false,'-','Java'),
(93,'CASSANDRA end point','com.datastax.driver.core.RequestHandler$SpeculativeExecution',' SpeculativeExecution : cassandraDB',12,false,'-','Java'),
(94,'HTTP end point','com.google.api.client.http.HttpRequest.execute()Lcom/google/api/client/http/HttpResponse;','Big Query',1,false,'-','Java'),
(95,'Big Table end point','com.google.cloud.bigtable.hbase.BigtableTable.put(Lorg/apache/hadoop/hbase/client/Put;)V','Big Table: Put',20,false,'-','Java'),
(96,'Big Table end point','com.google.cloud.bigtable.hbase.BigtableTable.get(Lorg/apache/hadoop/hbase/client/Get;)Lorg/apache/hadoop/hbase/client/Result;','Big Table: Get',20,false,'-','Java'),
(97,'Big Table end point','com.google.cloud.bigtable.hbase.BigtableTable.delete(Lorg/apache/hadoop/hbase/client/Delete;)V','Big Table: Delete',20,false,'-','Java'),
(98,'Microsoft SQL end point','com.microsoft.sqlserver.jdbc.SQLServerStatement','SQLServerStatement',21,false,'-','Java'),
(99,'Microsoft SQL end point','com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement','SQLServerPreparedStatement',21,false,'-','Java');


INSERT INTO config.naming_rule_profile_backendtype_asso(assoc_id,host ,port,prefix ,service_name,table_name,topic_name,url,databaseproduct_name,databaseproduct_version,driver_name,driver_Version,query,user_name,backend_type_id,profile_id) VALUES
(1,true,false,false,false,false,false,false,false,false,false,false,false,false,1,1),
(2,true,false,false,false,false,false,false,false,false,false,false,false,false,2,1),
(3,true,false,false,false,false,false,false,false,false,false,false,false,false,3,1),
(4,true,false,false,false,false,false,false,false,false,false,false,false,false,4,1),
(5,true,false,false,false,false,false,false,false,false,false,false,false,false,5,1),
(6,true,false,false,false,false,false,false,false,false,false,false,false,false,6,1),
(7,true,false,false,false,false,false,false,false,false,false,false,false,false,7,1),
(8,true,false,false,false,false,false,false,false,false,false,false,false,false,8,1),
(9,true,false,false,false,false,false,false,false,false,false,false,false,false,9,1),
(10,true,false,false,false,false,false,false,false,false,false,false,false,false,10,1),
(11,true,false,false,false,false,false,false,false,false,false,false,false,false,11,1),
(12,false,false,false,false,false,false,false,false,false,false,false,false,false,12,1),
(13,false,false,false,false,false,false,false,false,false,false,false,false,false,13,1),
(14,false,false,false,false,false,false,false,false,false,false,false,false,false,14,1),
(15,false,false,false,false,false,false,false,false,false,false,false,false,false,15,1),
(16,false,false,false,false,false,false,false,false,false,false,false,false,false,16,888888),
(17,false,false,false,false,false,false,false,false,false,false,false,false,false,17,888888),
(18,false,false,false,false,false,false,false,false,false,false,false,false,false,18,888888),
(19,true,false,false,false,false,false,false,false,false,false,false,false,false,19,1),
(20,true,false,false,false,false,false,false,false,false,false,false,false,false,20,1),
(21,true,false,false,false,false,false,false,false,false,false,false,false,false,21,1);

INSERT INTO config.profile_backend_point_asso(assoc_id,enabled,end_point_id,profile_id) VALUES
(1,true,1,1),
(2,true,2,1),
(3,true,3,1),
(4,true,4,1),
(5,true,5,1),
(6,true,6,1),
(7,true,7,1),
(8,true,8,1),
(9,true,9,1),
(10,true,10,1),
(11,true,11,1),
(12,true,12,1),
(13,false,13,1),
(14,true,14,1),
(15,true,15,1),
(16,false,16,1),
(17,false,17,1),
(19,true,19,1),
(20,true,20,1),
(21,true,21,1),
(22,true,22,1),
(23,true,23,1),
(24,true,24,1),
(25,true,25,1),
(26,true,26,1),
(27,true,27,1),
(28,true,28,1),
(29,true,29,1),
(30,true,30,1),
(31,true,31,1),
(32,true,32,1),
(33,false,33,1),
(34,true,34,1),
(35,false,35,1),
(36,true,36,1),
(37,true,37,1),
(38,true,38,1),
(39,false,39,1),
(40,false,40,1),
(41,false,41,1),
(42,true,42,1),
(43,true,43,1),
(44,true,44,1),
(45,true,45,1),
(46,false,46,1),
(47,false,47,1),
(48,false,48,1),
(49,false,49,1),
(50,false,50,1),
(51,false,51,1),
(52,true,52,1),
(53,true,53,1),
(54,false,54,1),
(55,true,55,1),
(56,true,56,1),
(57,true,57,1),
(58,true,58,1),
(59,true,59,1),
(60,true,60,1),
(61,true,61,1),
(62,true,62,1),
(63,true,63,1),
(64,true,64,1),
(65,true,65,1),
(66,true,66,1),
(67,false,67,1),
(68,false,68,1),
(69,false,69,1),
(70,true,70,888888),
(71,false,71,888888),
(72,true,72,888888),
(73,true,73,888888),
(74,true,74,888888),
(75,false,75,888888),
(76,true,76,888888),
(77,true,77,888888),
(78,true,78,888888),
(79,false,79,888888),
(80,true,80,888888),
(81,false,81,888888),
(82,true,82,888888),
(83,true,83,888888),
(84,true,84,888888),
(85,true,85,888888),
(86,true,86,1),
(87,true,87,1),
(88,true,88,1),
(89,true,89,1),
(90,true,90,1),
(91,true,91,1),
(92,true,92,1),
(93,true,93,1),
(94,true,94,1),
(95,true,95,1),
(96,true,96,1),
(97,true,97,1),
(98,true,98,1),
(99,true,99,1);


INSERT INTO config.headers_type(ht_id,header_type_name) VALUES
(1,'request'),
(2,'response'),
(3,'cookie');

INSERT INTO config.headers_meta_data(hmd_id,ht_id,header_name) VALUES
(1,1,'Accept-Charset'),
(2,1,'Accept-Datetime'),
(3,1,'Accept-Encoding'),
(4,1,'Accept-Language'),
(5,1,'Accept'),
(6,1,'Authorization'),
(7,1,'Cache-Control'),
(8,1,'Connection'),
(9,1,'Content-Length'),
(10,1,'Content-MD5'),
(11,1,'Content-Type'),
(12,1,'Cookie'),
(13,1,'DNT'),
(14,1,'Date'),
(15,1,'Expect'),
(16,1,'Front-End-Https'),
(17,1,'Host'),
(18,1,'If-Match'),
(19,1,'If-Modified-Since'),
(20,1,'If-None-Match'),
(21,1,'If-Range'),
(22,1,'If-Unmodified-Since'),
(23,1,'Max-Forwards'),
(24,1,'Origin'),
(25,1,'Pragma'),
(26,1,'Proxy-Authorization'),
(27,1,'If-Range'),
(28,1,'Proxy-Connection'),
(29,1,'Range'),
(30,1,'Referer'),
(31,1,'TE'),
(32,1,'Upgrade'),
(33,1,'User-Agent'),
(34,1,'Via'),
(35,1,'Warning'),
(36,1,'X-ATT-DeviceId'),
(37,1,'X-Forwarded-For'),
(38,1,'X-Forwarded-Proto'),
(39,1,'X-Requested-With'),
(40,1,'X-Wap-Profile'),
(41,2,'Accept-Ranges'),
(42,2,'Access-Control-Allow-Origin'),
(43,2,'Age'),
(44,2,'Allow'),
(45,2,'Cache-Control'),
(46,2,'Connection'),
(47,2,'Content-Disposition'),
(48,2,'Content-Encoding'),
(49,2,'Content-Language'),
(50,2,'Content-Length'),
(51,2,'Content-Location'),
(52,2,'Content-MD5'),
(53,2,'Content-Range'),
(54,2,'Content-Security-Policy'),
(55,2,'Content-Type'),
(56,2,'Date'),
(57,2,'ETag'),
(58,2,'Expires'),
(59,2,'Last-Modified'),
(60,2,'Link'),
(61,2,'Location'),
(62,2,'P3P'),
(63,2,'Pragma'),
(64,2,'Proxy-Authenticate'),
(65,2,'Refresh'),
(66,2,'Retry-After'),
(67,2,'Server'),
(68,2,'Set-Cookie'),
(69,2,'Status'),
(70,2,'Strict-Transport-Security'),
(71,2,'Trailer'),
(72,2,'Transfer-Encoding'),
(73,2,'Vary'),
(74,2,'Via'),
(75,2,'WWW-Authenticate'),
(76,2,'Warning'),
(77,2,'X-Content-Security-Policy'),
(78,2,'X-Content-Type-Options'),
(79,2,'X-Frame-Options'),
(80,2,'X-Powered-By'),
(81,2,'X-UA-Compatible'),
(82,2,'X-WebKit-CSP'),
(83,2,'X-XSS-Protection'),
(84,2,'Accept-Charset'),
(85,2,'Accept-Datetime'),
(86,2,'Accept-Encoding'),
(87,2,'Accept'),
(88,2,'Authorization'),
(89,2,'Cookie'),
(90,2,'DNT'),
(91,2,'Expect'),
(92,2,'Front-End-Https'),
(93,2,'Host'),
(94,2,'If-Match'),
(95,2,'If-Modified-Since'),
(96,2,'If-None-Match'),
(97,2,'If-Range'),
(98,2,'If-Unmodified-Since'),
(99,2,'Max-Forwards'),
(100,2,'Origin'),
(101,2,'Proxy-Authorization'),
(102,2,'Proxy-Connection'),
(103,2,'CavNDFPInstance'),
(104,2,'TE'),
(105,2,'Upgrade'),
(106,2,'User-Agent'),
(107,2,'X-ATT-DeviceId'),
(108,2,'X-Forwarded-For'),
(109,2,'X-Forwarded-Proto'),
(110,2,'X-Requested-With'),
(111,2,'X-Wap-Profile'),
(112,1,'CavNDFPInstance'),
(113,2,'Referer'),
(114,2,'Range');


INSERT INTO config.value_type(val_id,val_type) VALUES
(1,'String'),
(2,'Numeric'),
(3,'Others');


INSERT INTO config.conditional_operator(opt_id,val_id,operators) VALUES
(1,1,'='),
(2,1,'!='),
(3,1,'contains'),
(4,1,'!contains'),
(5,2,'='),
(6,2,'!='),
(7,2,'<'),
(8,2,'<='),
(9,2,'>'),
(10,2,'>='),
(11,3,'PRESENT'),
(12,3,'!PRESENT'),
(13,1,'PRESENT'),
(14,1,'!PRESENT'),
(15,2,'PRESENT'),
(16,2,'!PRESENT');

INSERT INTO config.bussiness_trans_global(bt_global_id, complete, dynamic_req_type, dynamic_req_value, http_method, request_header, request_param, segment_type, segment_uri,segment_value, slow_transaction, uri_type, very_slow_transaction, profile_id, slow_threshold, very_slow_threshold) VALUES
(1, false, false,'httpMethod', true, false, false, 'FromFirst', true, 2, 3000, 'segmentOfURI', 5000, 1, '10', '20'),
(2, false, false,'httpMethod', true, false, false, 'FromFirst', true, 2, 3000, 'segmentOfURI', 5000, 777777, '10', '20'),
(3, false, false,'httpMethod', true, false, false, 'FromFirst', true, 2, 3000, 'segmentOfURI', 5000, 888888, '10', '20');

INSERT INTO config.ndc_keywords(ndc_key_id, ndc_key_name, ndc_key_min, ndc_key_max, ndc_def_value,ndc_key_val )VALUES 
(1,'NDC_WAIT_TIME_AFTER_TEST_IS_OVER','','','30','30'),
(2,'NDC_CONTROL_MSG_ACK_TIMEOUT','','','10','10'),
(3,'NDC_CONTROL_THREAD_EPOLL_TIMEOUT','','','10',10),
(4,'NDC_CONTINUE_ON_CONTROL_CONNECTION_ERROR','','','2','2'),
(5,'NDC_TIME_TO_SEND_HEART_BEAT_TO_BCI','','','300','300'),
(6,'NDP_TR_RUNNING_STATUS_POLL_INTERVAL','','','500','500'),
(7,'NDP_NEW_RAW_DATA_POLL_INTERVAL','','','500','500'),
(8,'ENABLE_METHOD_TIMING_TABLE','','','1','1'),
(9,'NDP_OMIT_NON_NS_FLOWPATHS','','','1','1'),
(10,'NDP_EXCLUDE_FLOWPATHS_OUTSIDE_TESTIDX','','','1','1'),
(11,'NDP_TRACE_LEVEL','0','4','1','1'),
(12,'MAX_METHOD_CALL_STACK','1','10485760','128','128'),
(13,'NDP_INIT_CONCURRENT_FLOWPATHS','8','10485760','512','512'),
(14,'NDP_DELTA_CONCURRENT_FLOWPATHS','8','10485760','512','512'),
(15,'NDP_MAX_BUFFERED_META_DATA_BUFSIZE','8','1048576','64','64'),
(16,'NDP_MAX_BUFFERED_BCI_ARG_BUFSIZE','8','1048576','64','64'),
(17,'NDP_MAX_BUFFERED_HTTP_HEADER_MD_BUFSIZE','8','1048576','8','8'),
(18,'NDP_MAX_BUFFERED_HTTP_HEADER_BUFSIZE','8','1048576','64','64'),
(19,'NDP_MAX_BUFFERED_EXCEPTION_DATA_BUFSIZE','8','1048576','64','64'),
(20,'NDP_MAX_BUFFERED_FLOWPATH_BUFSIZE','8','1048576','512','512'),
(21,'NDP_MAX_BUFFERED_APPLOG_BUFSIZE','8','1048576','512','512'),
(22,'NDP_MAX_BUFFERED_METHOD_TIMING_TABLE_ENTRIES','8','1048576','1024','1024'),
(23,'NDP_MAX_BUFFERED_MEM_ALLOC_BUFSIZE','8','1048576','16','16'),
(24,'NDP_MAX_BUFFERED_SQL_TABLE_BUFSIZE','32','1048576','32','32'),
(25,'NDP_MAX_BUFFERED_SQL_RECORD_TABLE_BUFSIZE','8','1048576','16','16'),
(26,'NDP_DEBUG_LOGFILE_ROLLOVER_SIZE','1','102400','100','100'),
(27,'NDP_FORCE_UPLOAD_TIMEOUT','1','2592000000','10','10'),
(28,'NDP_SECS_TO_MARK_AN_FP_DEAD','0','43200','90','90'),
(29,'NDP_SECS_TO_CLEAN_DEAD_FLOWPATHS','0','43200','10','10'),
(30,'DB_UPLOAD_MODE','','','1','1'),
(31,'NDP_FORCE_ADD_URC_FOR_NS_FPI_IN_MAPPING_RECORD','','','0','0'),
(32,'NDP_MAX_ENTRY_EXIT_RECORDS_IN_AN_FP','0','10000000','110000','110000'),
(33,'NDP_LOWER_PROCESS_PRIORITY_FLAG','','','0','0'),
(34,'NDP_MAX_BUFFERED_JMS_BUFSIZE','8','1048576','32','32'),
(35,'NDP_MAX_CONCURRENT_THREADS_IN_JVM','','','512','512'),
(36,'NDP_METHOD_TIMING_CSV_FLUSH_INTERVAL_SECS','0','10000000','300','300'),
(37,'NDP_DISABLE_DUMPING_CAPTURED_HTTP_BODY','0','1','0','0'),
(38,'NDC_STOP_INSTRUMENTATION_RESPONSE_TIMEOUT','','','300000','300000'),
(39,'NDC_ACCEPT_NEW_AND_CLOSE_CURRENT_DATA_CONNECTION','','','1','1'),
(40,'NDC_DATA_THD_TERM_RETRY_COUNT','','','50','50'),
(41,'NDC_DATA_THD_TERM_RETRY_INTERVAL_MSEC','','','200000','200000'),
(42,'SND_RESP_TO_BCI_ON_DATA_CONN','','','0','0'),
(43,'NDC_LOG_BCI_AGGREGATE_RAW_DATA','','','0','0'),
(44,'NDP_SEQ_BLOB_IN_FILE_MIN_SIZE','1','2048','64','64'),
(45,'NDP_SEQ_BLOB_COMPRESSION_BUFFER_INIT_SIZE','1','2048','1024','1024'),
(46,'MAX_BUFFERED_SQB_BUFSIZE','8','1024000','8192','8192'),
(47,'NDC_WAIT_TIME_TO_SEND_FORCE_STOP_COMP_SIG','','','60','60'),
(48,'NDP_DUMP_URC','','','0','0'),
(49,'NDP_META_DATA_RECOVERY_RETRY_TIMEOUT_IN_SEC','','','60','60'),
(50,'NDP_SQL_START_NORM_ID','0','2000000000','0','0'),
(51,'NDP_ENABLE_SQL_TIMING','','','1','1'),
(52,'NDP_ENABLE_SQL_RECORD','','','0','0'),
(53,'NDP_ENABLE_BCIARG','','','1','1'),
(54,'NDDBU_CHUNK_SIZE','','','134217728','134217728'),
(55,'NDDBU_IDLE_TIME','','','5','5'),

(57,'NDP_FORCE_ADD_URC_FOR_MISSING_FP_MAPPING_RECORD','','','0','0'),
(58,'NDP_FREE_FP_MIN_SQB_SIZE','','','32768','32768'),
(59,'NDP_RAW_DATA_BUF_SIZE','','','262144','262144'),
(60,'NDP_GENERATE_FP_SIGNATURES','','','0','0'),
(61,'NDP_MIN_RESPTIME_TO_FILTER_L1_FP','','','0','0'),
(62,'NDP_BINARY_FORMAT_FOR_METHOD_TIMING','','','1','1'),
(63,'NDC_BCI_TIME_DIFF_THRESHOLD_IN_MS','','','0','0'),
(64,'NDC_HS_ST_IN_FILE_MIN_SIZE','1','2000000000','64','64'),
(65,'NDC_HS_ST_COMPRESSION_BUFFER_INIT_SIZE','1','2000000000','1024','1024'),
(66,'ND_ENABLE_MONITOR_LOG','','','0','0'),
(67,'NDP_MAX_ENTRY_EXIT_RECORDS_IN_AN_FP_EX2','','','1000000','1000000'),
(68,'ENABLE_AUTO_SCALING','','','0','0'),
(69,'NDC_MODIFY_TOPO_ENTRY','','','1','1'),
(70,'NDC_DATA_THD_TERM_RETRY_INTERVAL_SEC','','','20','20'),
(71,'NDP_DEBUG_LOGLEVEL','0','4','0','0'),
(72,'NDC_REUSE_INSTANCE_ID_TIME_IN_MIN','','','0','0'),
(73,'NDP_ENABLE_METADATA_RECOVERY','','','1','1'),
(74,'NDP_ALLOW_REQ_DETAIL_BEFORE_SQB_BEGIN_REC','','','1','1'),
(75,'NDC_LOG_BCI_AGGREGATE_RAW_DATA_EX','','','0','0'),
(76,'NDC_BCI_RESPONSE_TIME_FOR_METADATA_IN_SECS','','','60','60'),
(77,'ENABLE_FP_STAT_MONITOR','','','0','0'),
(78,'SEND_ACTIVE_INSTANCE_REP','','','1','1'),
(79,'NDC_MAX_CTRL_CON','','','400','400'),
(80,'NDP_MAX_SQL_INDEX_FROM_BCI','','','4096','4096'),
(81,'NDC_TRACING_LEVEL','','','1 50','1 50'),
(83,'NDP_SEQ_BLOB_IN_FILE_FLAG','','','1 B 10000','1 B 10000'),
(85,'NDC_HS_ST_IN_FILE_FLAG','','','1 B','1 B'),
(86,'ND_ENABLE_CAPTURE_DB_TIMING','','','1 0 0 0','1 0 0 0'),
(87,'NDC_THRESHOLD_TIME_TO_MARK_APP_INACTIVE','','','3600000 600000','3600000 600000'),
(88,'NDDBU_TMP_FILE_PATH','','','/mnt/tmp','/mnt/tmp'),
(89,'ND_FPI_MASK','','','NDEID:56:4;AppID:46:10;TS:8:38;SeqNo:0:8;','NDEID:56:4;AppID:46:10;TS:8:38;SeqNo:0:8;'),
(90,'NDC_THRESHOLD_TO_MARK_DELETED','','','1 8h','1 8h'),
(91,'NDP_DELETED_INSTANCE_CLEANUP_DELAY','','','3','3');


INSERT INTO config.container_type(container_id,description,container_type,container_name) VALUES
(1,'Asynchronous Transaction Rules for Jetty application','Jetty','jetty'),
(2,'Asynchronous Transaction Rules for Tomcat application','Tomcat','tomcat'),
(3,'Asynchronous Transaction Rules for Weblogic application','Weblogic','weblogic');


INSERT INTO config.nd_asynchronous_rule(async_rule_id,fqm,container_id,rule_type,dump_mode) VALUES
(1,'org.eclipse.jetty.server.Request.startAsync()Ljavax/servlet/AsyncContext;',1,'start',0),
(2,'org.eclipse.jetty.server.Request.startAsync(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)Ljavax/servlet/AsyncContext;',1,'start',0),
(3,'org.eclipse.jetty.server.AsyncContextState.dispatch(Ljavax/servlet/ServletContext;Ljava/lang/String;)V',1,'dispatch',2),
(4,'org.eclipse.jetty.server.AsyncContextState.dispatch(Ljava/lang/String;)V',1,'dispatch',2),
(5,'org.eclipse.jetty.server.AsyncContextState.dispatch()V',1,'dispatch',2),
(6,'org.eclipse.jetty.server.AsyncContextState.complete()V',1,'complete',2),
(7,'weblogic.servlet.internal.ServletRequestImpl.startAsync(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;Z)Ljavax/servlet/AsyncContext;',3,'start',0),
(8,'weblogic.servlet.internal.ServletRequestImpl.startAsync()Ljavax/servlet/AsyncContext;',3,'start',0),
(9,'weblogic.servlet.internal.ServletRequestImpl.startAsync(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse)Ljavax/servlet/AsyncContext;',3,'start',0),
(10,'weblogic.servlet.internal.async.AsyncContextImpl.dispatch()V',3,'dispatch',2),
(11,'weblogic.servlet.internal.async.AsyncContextImpl.dispatch(Ljava/lang/String;)V',3,'dispatch',2),
(12,'weblogic.servlet.internal.async.AsyncContextImpl.dispatch(Ljavax/servlet/ServletContext;Ljava/lang/String;)V',3,'dispatch',2),
(13,'weblogic.servlet.internal.async.AsyncContextImpl.complete()V',3,'complete',2),
(14,'org.apache.catalina.connector.Request.startAsync()Ljavax/servlet/AsyncContext;',2,'start',0),
(15,'org.apache.catalina.connector.Request.startAsync(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)Ljavax/servlet/AsyncContext;',2,'start',0),
(16,'org.apache.catalina.core.AsyncContextImpl.dispatch(Ljavax/servlet/ServletContext;Ljava/lang/String;)V',2,'dispatch',2),
(17,'org.apache.catalina.core.AsyncContextImpl.dispatch(Ljava/lang/String;)V',2,'dispatch',2),
(18,'org.apache.catalina.core.AsyncContextImpl.dispatch()V',2,'dispatch',2),
(19,'org.apache.catalina.core.AsyncContextImpl.complete()V',2,'complete',2);

INSERT INTO config.profile_async_type_assoc(assoc_id,container_id,enabled,profile_id) VALUES
(1,1,true,1),
(2,2,true,1),
(3,3,true,1);

COMMIT;
+

CREATE SEQUENCE config.hibernate_sequence START WITH 1 INCREMENT BY 1 NO CYCLE;