#! /bin/sh

BEGIN;

INSERT INTO config.profile(profile_id,profile_name,profile_desc,controller_name,agent) VALUES
(1,'default_Java','Default profile for Java','-','Java'),
(777777,'default_NodeJS','Default profile for Node JS','-','NodeJS'),
(888888,'default_DotNet','Default profile for Dot Net','-','Dot Net');

INSERT INTO config.entry_type(entry_type_id, entry_type_name, entry_type_detail) VALUES
(1,'HttpServletService','description'),
(2,'EntryForWebLogicJSP','description'),
(3,'ApacheJsperService','description'),
(4,'JerseyCall', 'description'),
(5,'GlassFishJersey', 'description'),
(6,'Generic', 'description'),
(7,'JMSCall', 'description'),
(8,'EntryForJBOSS', 'description'),
(9,'ErrorPageEntry','description'),
(10,'HessianCallOut','description'),
(11,'ATGServlet','description'),
(12,'TXExit','description');

INSERT INTO config.service_entry_points(entry_id,entry_desc,entry_fqm,entry_name,entry_type_id,custom_entry,module,agent) VALUES
(1,'Fully qualified name for the service method for HttpServlet Class','javax.servlet.http.HttpServlet.service(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V','HttpServlet.service', 1,false,'-','Java'),
(2,'fully qualified name for the doFilter method for weblogic','weblogic.servlet.internal.FilterChainImpl.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','FilterChainImpl.doFilter', 2,false,'-','Java'),
(3,' ','org.apache.jasper.runtime.HttpJspBase.service(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V','ApacheJsperService', 3,false,'-','Java'),
(4,' ','weblogic.servlet.jsp.JspBase.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','WebAppFilterChain.doFilter', 2,false,'-','Java'),
(5,' ','com.ibm.ws.webcontainer.servlet.ServletWrapper.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','ServletWrapper.service', 2,false,'-','Java'),
(6,' ','com.ibm.ws.webcontainer.servlet.ServletWrapper.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;Lcom/ibm/ws/webcontainer/webapp/WebAppServletInvocationEvent;)V','ServletWrapper.service-WebAppServletInvocationEvent', 2,false,'-','Java'),
(7,' ','org.apache.catalina.core.ApplicationFilterChain.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','ApplicationFilterChain.doFilter', 8,false,'-','Java'),
(8,' ','org.glassfish.jersey.servlet.ServletContainer.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','ServletContainer.service', 5,false,'-','Java'),
(9,' ','com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','WebAppFilterChain.doFilter', 2,false,'-','Java'),
(10,' ','weblogic.servlet.internal.RequestDispatcherImpl.forward(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','RequestDispatcherImpl.forward',9,false,'-','Java'),
(11,' ','com.caucho.hessian.server.HessianServlet.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','HessianServlet.service',10,false,'-','Java'),
(12,' ' ,'atg.servlet.pipeline.PipelineableServletImpl.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V', 'PipelineableServletImpl.service',11,false,'-','Java'),
(13,' ','atg.servlet.DynamoServlet.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','DynamoServlet.service',11,false,'-','Java'),
(14,' ','atg.servlet.sessionsaver.SessionSaverServlet.service(Latg/servlet/DynamoHttpServletRequest;Latg/servlet/DynamoHttpServletResponse;)V', 'SessionSaverServlet.service',11,false,'-','Java'),
(15,' ','atg.servlet.pipeline.HeadPipelineServlet.service(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V', 'HeadPipelineServlet.service',11,false,'-','Java'),
(16,' ','org.apache.activemq.ActiveMQMessageConsumer.dispatch(Lorg/apache/activemq/command/MessageDispatch;)V','ActiveMQMessageConsumer.dispatch',7,false,'-','Java'),
(17,' ','com.ibm.mq.jms.MQMessageConsumer$FacadeMessageListener.onMessage(Ljavax/jms/Message;)V','MQMessageConsumer$FacadeMessageListener.onMessage',7,false,'-','Java'),
(18,' ','System.Web.HttpRuntime.ProcessRequestNotificationPrivate','ProcessRequestNotificationPrivate',1,false,'System.Web.dll','Dot Net'),
(19,' ','System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper','ProcessRequestNotificationHelper',1,false,'System.Web.dll','Dot Net'),
(20,' ','System.Web.HttpRuntime.FinishPipelineRequest','FinishPipelineRequest',12,false,'System.Web.dll','Dot Net'),
(21,' ','System.Web.HttpRuntime.FinishRequest','FinishRequest',12,false,'System.Web.dll','Dot Net'),
(22,' ','org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V','ServletHandler$CachedChain.doFilter',1,false,'-','Java'),
(23,' ','org.springframework.web.filter.OncePerRequestFilter.doFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;Ljavax/servlet/FilterChain;)V','OncePerRequestFilter.doFilter',1,false,'-','Java'),
(24,' ','com.sun.jersey.spi.container.servlet.WebComponent.service(Ljava/net/URI;Ljava/net/URI;Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)I','WebComponent.service(URI,URI,HttpServletRequest,HttpServletResponse)',4,false,'-','Java'),
(25,' ','com.tibco.plugin.share.http.servlet.BwServlet.doGet(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V','doGet(HttpServletRequest,HttpServletResponse)',1,false,'-','Java'),
(26,' ','com.tibco.plugin.share.http.servlet.BwServlet.doPost(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V','doPost(HttpServletRequest,HttpServletResponse)',1,false,'-','Java'),
(27,' ','com.tibco.plugin.share.http.servlet.BwServlet.doPut(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V','doPut(HttpServletRequest,HttpServletResponse)',1,false,'-','Java'),
(28,' ','com.tibco.plugin.share.http.servlet.BwServlet.doDelete(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V','doDelete(HttpServletRequest,HttpServletResponse)',1,false,'-','Java'),
(29,' ','com.tibco.plugin.share.http.servlet.BwServlet.doOptions(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V','doOptions(HttpServletRequest,HttpServletResponse)',1,false,'-','Java'),
(30,' ','com.tibco.plugin.share.http.servlet.BwServlet.a(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;Ljava/lang/String;)V','a(HttpServletRequest,HttpServletResponse,String)',1,false,'-','Java'),
(31,' ','org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(Ljavax/jms/Session;Ljavax/jms/Message;)V','invokeListener(Session,Message)',7,false,'-','Java'),
(32,' ','org.springframework.batch.core.job.AbstractJob.execute(Lorg/springframework/batch/core/JobExecution;)V','AbstractJob_Execute',6,false,'-','Java'),
(33,' ','org.springframework.batch.core.job.SimpleJob.doExecute(Lorg/springframework/batch/core/JobExecution;)V','SimpleJob_doExecute',6,false,'-','Java');


INSERT INTO config.profile_service_entry_asso(prof_entry_id, profile_enable, entry_id, profile_id) VALUES
(1, true, 1, 1),
(2, true, 2, 1),
(3, true, 3, 1),
(4, true, 4, 1),
(5, true, 5, 1),
(6, true, 6, 1),
(7, true, 7, 1),
(8, false, 8, 1),
(9, true, 9, 1),
(10, true, 10, 1),
(11, true, 11, 1),
(12, false, 12, 1),
(13, false, 13, 1),
(14, false, 14, 1),
(15, false, 15, 1),
(16, false, 16, 1),
(17, false, 17, 1),
(18, true, 18, 888888),
(19, true, 19, 888888),
(20, true, 20, 888888),
(21, true, 21, 888888),
(22, true, 22, 1),
(23, true, 23, 1),
(24, false, 24,1),
(25, true, 25, 1),
(26, true, 26, 1),
(27, true, 27, 1),
(28, true, 28, 1),
(29, true, 29, 1),
(30, true, 30, 1),
(31, false, 31, 1),
(32, false, 32, 1),
(33, false, 33, 1);


INSERT INTO config.keywords_meta_data(kmd_id,key_type,key_type_id) VALUES
(1,'char','0'),
(2,'integer','1'),
(3,'double','2'),
(4,'long long','3'),
(5,'string','4'),
(6,'file','5');

INSERT INTO config.ndc_keywords(ndc_key_id, ndc_key_name, ndc_key_min, ndc_key_max, ndc_def_value,ndc_key_val,ndc_key_type) VALUES 
(1,'NDC_WAIT_TIME_AFTER_TEST_IS_OVER','','','30','30',''),
(2,'NDC_CONTROL_MSG_ACK_TIMEOUT','','','10','10',''),
(3,'NDC_CONTROL_THREAD_EPOLL_TIMEOUT','','','10',10,''),
(4,'NDC_CONTINUE_ON_CONTROL_CONNECTION_ERROR','','','2','2',''),
(5,'NDC_TIME_TO_SEND_HEART_BEAT_TO_BCI','','','300','300',''),
(6,'NDP_TR_RUNNING_STATUS_POLL_INTERVAL','','','500','500',''),
(7,'NDP_NEW_RAW_DATA_POLL_INTERVAL','','','500','500',''),
(8,'ENABLE_METHOD_TIMING_TABLE','','','1','1',''),
(9,'NDP_OMIT_NON_NS_FLOWPATHS','','','1','1',''),
(10,'NDP_EXCLUDE_FLOWPATHS_OUTSIDE_TESTIDX','','','1','1',''),
(11,'NDP_TRACE_LEVEL','0','4','1','1',''),
(12,'MAX_METHOD_CALL_STACK','1','10485760','128','128',''),
(13,'NDP_INIT_CONCURRENT_FLOWPATHS','8','10485760','512','512',''),
(14,'NDP_DELTA_CONCURRENT_FLOWPATHS','8','10485760','512','512',''),
(15,'NDP_MAX_BUFFERED_META_DATA_BUFSIZE','8','1048576','64','64',''),
(16,'NDP_MAX_BUFFERED_BCI_ARG_BUFSIZE','8','1048576','64','64',''),
(17,'NDP_MAX_BUFFERED_HTTP_HEADER_MD_BUFSIZE','8','1048576','8','8',''),
(18,'NDP_MAX_BUFFERED_HTTP_HEADER_BUFSIZE','8','1048576','64','64',''),
(19,'NDP_MAX_BUFFERED_EXCEPTION_DATA_BUFSIZE','8','1048576','64','64',''),
(20,'NDP_MAX_BUFFERED_FLOWPATH_BUFSIZE','8','1048576','512','512',''),
(21,'NDP_MAX_BUFFERED_APPLOG_BUFSIZE','8','1048576','512','512',''),
(22,'NDP_MAX_BUFFERED_METHOD_TIMING_TABLE_ENTRIES','8','1048576','1024','1024',''),
(23,'NDP_MAX_BUFFERED_MEM_ALLOC_BUFSIZE','8','1048576','16','16',''),
(24,'NDP_MAX_BUFFERED_SQL_TABLE_BUFSIZE','32','1048576','32','32',''),
(25,'NDP_MAX_BUFFERED_SQL_RECORD_TABLE_BUFSIZE','8','1048576','16','16',''),
(26,'NDP_DEBUG_LOGFILE_ROLLOVER_SIZE','1','102400','100','100',''),
(27,'NDP_FORCE_UPLOAD_TIMEOUT','1','2592000000','10','10',''),
(28,'NDP_SECS_TO_MARK_AN_FP_DEAD','0','43200','90','90',''),
(29,'NDP_SECS_TO_CLEAN_DEAD_FLOWPATHS','0','43200','10','10',''),
(30,'DB_UPLOAD_MODE','','','1','1',''),
(31,'NDP_FORCE_ADD_URC_FOR_NS_FPI_IN_MAPPING_RECORD','','','0','0',''),
(32,'NDP_MAX_ENTRY_EXIT_RECORDS_IN_AN_FP','0','10000000','110000','110000',''),
(33,'NDP_LOWER_PROCESS_PRIORITY_FLAG','','','0','0',''),
(34,'NDP_MAX_BUFFERED_JMS_BUFSIZE','8','1048576','32','32',''),
(35,'NDP_MAX_CONCURRENT_THREADS_IN_JVM','','','512','512',''),
(36,'NDP_METHOD_TIMING_CSV_FLUSH_INTERVAL_SECS','0','10000000','300','300',''),
(37,'NDP_DISABLE_DUMPING_CAPTURED_HTTP_BODY','0','1','0','0',''),
(38,'NDC_STOP_INSTRUMENTATION_RESPONSE_TIMEOUT','','','300000','300000',''),
(39,'NDC_ACCEPT_NEW_AND_CLOSE_CURRENT_DATA_CONNECTION','','','1','1',''),
(40,'NDC_DATA_THD_TERM_RETRY_COUNT','','','50','50',''),
(41,'NDC_DATA_THD_TERM_RETRY_INTERVAL_MSEC','','','200000','200000',''),
(42,'SND_RESP_TO_BCI_ON_DATA_CONN','','','0','0',''),
(43,'NDC_LOG_BCI_AGGREGATE_RAW_DATA','','','0','0',''),
(44,'NDP_SEQ_BLOB_IN_FILE_MIN_SIZE','1','2048','64','64',''),
(45,'NDP_SEQ_BLOB_COMPRESSION_BUFFER_INIT_SIZE','1','2048','1024','1024',''),
(46,'MAX_BUFFERED_SQB_BUFSIZE','8','1024000','8192','8192',''),
(47,'NDC_WAIT_TIME_TO_SEND_FORCE_STOP_COMP_SIG','','','60','60',''),
(48,'NDP_DUMP_URC','','','0','0',''),
(49,'NDP_META_DATA_RECOVERY_RETRY_TIMEOUT_IN_SEC','','','60','60',''),
(50,'NDP_SQL_START_NORM_ID','0','2000000000','0','0',''),
(51,'NDP_ENABLE_SQL_TIMING','','','1','1',''),
(52,'NDP_ENABLE_SQL_RECORD','','','0','0',''),
(53,'NDP_ENABLE_BCIARG','','','1','1',''),
(54,'NDDBU_CHUNK_SIZE','','','134217728','134217728',''),
(55,'NDDBU_IDLE_TIME','','','5','5',''),
(57,'NDP_FORCE_ADD_URC_FOR_MISSING_FP_MAPPING_RECORD','','','0','0',''),
(58,'NDP_FREE_FP_MIN_SQB_SIZE','','','32768','32768',''),
(59,'NDP_RAW_DATA_BUF_SIZE','','','262144','262144',''),
(60,'NDP_GENERATE_FP_SIGNATURES','','','0','0',''),
(61,'NDP_MIN_RESPTIME_TO_FILTER_L1_FP','','','0','0',''),
(62,'NDP_BINARY_FORMAT_FOR_METHOD_TIMING','','','1','1',''),
(63,'NDC_BCI_TIME_DIFF_THRESHOLD_IN_MS','','','0','0',''),
(64,'NDC_HS_ST_IN_FILE_MIN_SIZE','1','2000000000','64','64',''),
(65,'NDC_HS_ST_COMPRESSION_BUFFER_INIT_SIZE','1','2000000000','1024','1024',''),
(66,'ND_ENABLE_MONITOR_LOG','','','0','0',''),
(67,'NDP_MAX_ENTRY_EXIT_RECORDS_IN_AN_FP_EX2','','','1000000','1000000',''),
(68,'ENABLE_AUTO_SCALING','','','0','0',''),
(69,'NDC_MODIFY_TOPO_ENTRY','','','1','1',''),
(70,'NDC_DATA_THD_TERM_RETRY_INTERVAL_SEC','','','20','20',''),
(71,'NDP_DEBUG_LOGLEVEL','0','4','0','0',''),
(72,'NDC_REUSE_INSTANCE_ID_TIME_IN_MIN','','','0','0',''),
(73,'NDP_ENABLE_METADATA_RECOVERY','','','1','1',''),
(74,'NDP_ALLOW_REQ_DETAIL_BEFORE_SQB_BEGIN_REC','','','1','1',''),
(75,'NDC_LOG_BCI_AGGREGATE_RAW_DATA_EX','','','0','0',''),
(76,'NDC_BCI_RESPONSE_TIME_FOR_METADATA_IN_SECS','','','60','60',''),
(77,'ENABLE_FP_STAT_MONITOR','','','0','0',''),
(78,'SEND_ACTIVE_INSTANCE_REP','','','1','1',''),
(79,'NDC_MAX_CTRL_CON','','','400','400',''),
(80,'NDP_MAX_SQL_INDEX_FROM_BCI','','','4096','4096',''),
(81,'NDC_TRACING_LEVEL','','','1 50','1 50',''),
(83,'NDP_SEQ_BLOB_IN_FILE_FLAG','','','1 B 10000','1 B 10000',''),
(85,'NDC_HS_ST_IN_FILE_FLAG','','','1 B','1 B',''),
(86,'ND_ENABLE_CAPTURE_DB_TIMING','','','1 0 0 0','1 0 0 0',''),
(87,'NDC_THRESHOLD_TIME_TO_MARK_APP_INACTIVE','','','3600000 600000','3600000 600000',''),
(88,'NDDBU_TMP_FILE_PATH','','','/mnt/tmp','/mnt/tmp',''),
(89,'ND_FPI_MASK','','','NDEID:56:4;AppID:46:10;TS:8:38;SeqNo:0:8;','NDEID:56:4;AppID:46:10;TS:8:38;SeqNo:0:8;',''),
(90,'NDC_THRESHOLD_TO_MARK_DELETED','','','1 8h','1 8h',''),
(91,'NDP_DELETED_INSTANCE_CLEANUP_DELAY','0','','3D','3D',''),
(92,'SND_RESP_TO_BCI_ON_DATA_CONN','0','1','0','0',''),
(93,'SEND_NDCOLLECTOR_IP','0','1','1','1','NDC'),
(94,'AUTO_SCALE_BLOCKED_TIER','','','','','NDC'),
(95,'AUTO_SCALE_ALLOWD_TIER','','','','','NDC'),
(96,'NDP_EXTENDED_METADATA','0','1','0','0','NDP'),
(97,'NDP_MAX_BEGIN_SEQ_LEN','0','256','256','256','NDP'),
(98,'NDP_FREE_FP_MEM_ON_COMPLETION','0','1','0','0','NDP'),
(99,'NDP_MEMPOOL_SETTINGS','','','','','NDP'),
(100,'NDP_MONITORS','','','','','NDP'),
(101,'NDP_ENABLE_SQL_METADATA_RECOVERY','0','1','1','1','NDP'),
(102,'NDP_THRESHOLD_DIFF_BET_FP_AND_ENTRY_MTD_RESPTIME_SEC','','','900','900','NDP'),
(144,'captureHTTPReqL1Fp','1','1048576','5','2','pre-custom','1'),
(145,'captureHTTPRespL1Fp','1','1048576','5','1','pre-custom','1'),
(146,'captureHTTPReqBodyL1Fp','1','1048576','5','0','pre-custom','1'),
(147,'captureHTTPReqBodyFullFp','1','1048576','5','0','pre-custom','1'),
(148,'captureHTTPRespBodyL1Fp','1','1048576','5','0','pre-custom','1'),
(149,'captureHTTPRespBodyFullFp','1','1048576','5','0','pre-custom','1'),
(150,'hdrListForValueAsId','0','4096','5','Content-Encoding,Host,Server,Transfer-Encoding','pre-custom','5'),
(151,'NDHTTPReqHdrCfgListL1Fp','1','1024','6','NA','pre-custom','5'),
(152,'maxHttpBodySize','0','1048576','2','1024','pre-custom','5'),
(153,'ASStateReport','0','1','2','1','pre-custom','1'),
(154,'ASDoNotFilterBlocked','0','1','2','0','pre-custom','1'),
(155,'ASAllocateDataBuffOnFailure','0','1','2','0','pre-custom','1'),
(156,'threadCleanUpCount','0','50','2','5','pre-custom','1'),
(157,'ndHttpCondMonFileList','1','1024','6','NA','pre-custom','1'),
(158,'setCavNVCookie','0','10240','5','0','pre-custom','1'),
(159,'ndMethodMonFileList','1','1024','6','NA','pre-custom','1'),
(160,'ndExceptionMonFileList','1','1024','6','NA','pre-custom','1'),
(161,'FPGMode','0','2','1','2','pre-custom','1'),
(162,'fpVersionID','0','10240','5','1.0','pre-custom','5'),
(163,'ndDynamicDiagnosticsConfFile','1','1024','6','NA','pre-custom','1'),
(164,'threadIdleTimeout','0','2147483647','2','10','pre-custom','1'),
(165,'NDP_ALLOW_FP_TO_START_WITH_SEQNUM_OTHER_THAN_1','0','1','1','0','pre-custom','1'),
(166,'ASReportBufferMaxSize','1','2147483647','4','262144','pre-custom','1'),
(167,'BTTConfig','1','1024','6','NA','pre-custom','7'),
(168,'enableDCHeartBeat','0','3600','2','0','pre-custom','7'),
(169,'DBIPName','0','1024','5','-','pre-custom','5'),
(170,'backendErrorDetectionMode','0','2048','5','3','pre-custom','1'),
(171,'enableUpdateLogMsgForNF','0','1','1','0','pre-custom','1'),
(172,'BTRuleOverridePolicy','0','2','1','1','pre-custom','5'),
(173,'ndEnableTxHotspot','0','1','2','1','pre-custom','5'),
(174,'ndHelperDepth','0','10','2','2','pre-custom','5'),
(175,'ndHotspotThreadLimit','0','10','2','0','pre-custom','5'),
(176,'enableCheckAdapter','0','1','2','1','pre-custom','1'),
(177,'groupedQueryThreshold','0','3600000','2','0','pre-custom','1'),
(178,'maxFieldValueLength','0','1048576','2','4096','pre-custom','1'),
(179,'maxRecordValueLength','0','4194304','2','16384','pre-custom','1'),
(180,'bciLogSleepInterval','0','30000','4','300','pre-custom','1'),
(181,'enableIPStatusCode','0','1','2','0','pre-custom','1'),
(182,'enableExecuteBatch','0','1','2','0','pre-custom','1'),
(183,'enableExSrcTraceLevel','0','2048','2','0','pre-custom','1'),
(184,'BCILoggingMode','0','2048','5','FILE','pre-custom','1'),
(185,'SafetyNetClassTypesFile','1','1024','6','NA','pre-custom','1'),
(186,'threadDumpFormat','0','1','2','1','pre-custom','1'),
(187,'statusCodeAccessible','0','1','2','1','pre-custom','1'),
(188,'maxAsyncDetailMapSize','0','100000','2','10000','pre-custom','1'),
(189,'dynamicSlowVslowThreshold','0','1','2','0','pre-custom','2'),
(190,'ndILRewritterFile','0','2048','6','NA','pre-custom','5'),
(191,'ndModuleFile','0','2048','6','NA','pre-custom','5'),
(192,'ndProcessesFile','0','2048','6','NA','pre-custom','5'),
(193,'ndPoolFile','0','2048','6','NA','pre-custom','5');


INSERT INTO config.backend_type(backend_type_id,backend_type_detail,backend_type_name,backend_type_name_entrypointsfile,backend_type_name_rulefile,agent) VALUES
(1,'HTTP Backend','HTTP','HttpCallout','HTTP','Java'),
(2,'Web Services Backend','Web Services','HttpCallout','WS','Java'),
(3,'JDBC Backend','JDBC','oracleDB','JDBC','Java'),
(4,'Coherence Backend','Coherence','HttpCallout','None','Java'),
(5,'RMI Backend','RMI','HttpCallout','RMI','Java'),
(6,'Mem Cache Backend','Mem Cache','HttpCallout','None','Java'),
(7,'Cloudant Backend','Cloudant','HttpCallout','None','Java'),
(8,'Hadoop Backend','Hadoop','HttpCallout','HBASE','Java'),
(9,'Custom  Backend','Custom','CustomCallout:','None','Java'),
(10,'Redis Backend','Redis','redis','REDIS','Java'),
(11,'Mongo Backend','Mongo','mongodb','MONGO','Java'),
(12,'Cassandra Backend','Cassandra','cassandra','None','Java'),
(13,'Custom Log Backend','Custom Log','CustomLog','None','Java'),
(14,'Custom Error Log Backend','Custom Error Log','CustomErrorlog','None','Java'),
(15,'Thread Backend','Thread','Thread','None','Java'),
(16,'HTTP Backend For Dot Net','HTTP','HTTP_CALLOUT','HTTP','Dot Net'),
(17,'SQL Backend For Dot Net','SQL','SQL_CALLOUT','SQL','Dot Net'),
(18,'Async Call For Dot Net','Async_Call','ASYNC_CALL','ASYNC_CALL','Dot Net'),
(19,'Cloudant NoSQL Backend','Cloudant NoSQL','cloudantEntry','CLOUDANT','Java'),
(20,'Big Table Backend','Big Table','bigTable','None','Java'),
(21,'Microsoft SQL Backend','Microsoft SQL','microsoftDB','None','Java'),
(22,'Log Backend','Log','Log','None','Java'),
(23,'Exception Backend','Exception','Exception','None','Java'),
(24,'XATransaction Backend','XATransaction','XATransaction','None','Java'),
(26,'Neo4j DB Callout Backend','Neo4j DB Callout','neo4jDB','NEO4J','Java'),
(27,'JMS Backend','JMS','HttpCallout','JMS','Java'),
(28,'Custom Backend','Custom','CUSTOM_ENTRY','None','Dot Net');



INSERT INTO config.backend_points(end_point_id,end_point_desc,end_point_fqm,end_point_name,backend_type_id,custom_entry,module,agent) VALUES
(1,'HTTP end point','org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Lorg/apache/commons/httpclient/HttpMethod;)V','Apace HTTP Client',1,false,'-','Java'),
(2,'HTTP end point','com.endeca.navigation.HttpENEConnection.query(Lcom/endeca/navigation/ENEQuery;)Lcom/endeca/navigation/ENEQueryResults;','Endeca',1,false,'-','Java'),
(3,'HTTP end point','org.apache.http.impl.client.AbstractHttpClient.execute(Lorg/apache/http/HttpHost;Lorg/apache/http/HttpRequest;Lorg/apache/http/protocol/HttpContext;)Lorg/apache/http/HttpResponse;','Apache AbstractHttpClient',1,false,'-','Java'),
(4,'HTTP end point','org.apache.http.impl.client.DefaultRequestDirector.execute(Lorg/apache/http/HttpHost;Lorg/apache/http/HttpRequest;Lorg/apache/http/protocol/HttpContext;)Lorg/apache/http/HttpResponse;','Apache Default HTTP Client',1,false,'-','Java'),
(5,'HTTP end point','org.apache.wink.client.internal.handlers.HttpURLConnectionHandler.processRequest(Lorg/apache/wink/client/ClientRequest;Lorg/apache/wink/client/handlers/HandlerContext;)Ljava/net/HttpURLConnection;','Apache Wink Client',1,false,'-','Java'),
(6,'HTTP end point','com.worklight.adapters.http.HTTPConnectionManager.execute(Lorg/apache/http/HttpRequest;Lorg/apache/http/protocol/HttpContext;)Lorg/apache/http/HttpResponse;','MFP Worklight HTTP Client',1,false,'-','Java'),
(7,'HTTP end point','org.springframework.web.client.RestTemplate.doExecute(Ljava/net/URI;Lorg/springframework/http/HttpMethod;Lorg/springframework/web/client/RequestCallback;Lorg/springframework/web/client/ResponseExtractor;)Ljava/lang/Object;','Spring REST Template Client',1,false,'-','Java'),
(8,'HTTP end point','org.springframework.web.client.RestTemplate\$HttpEntityRequestCallback.doWithRequest(Lorg/springframework/http/client/ClientHttpRequest;)V','Spring add Header in REST Callback Template Client',1,false,'-','Java'),
(9,'HTTP end point','org.springframework.http.client.support.HttpAccessor.createRequest(Ljava/net/URI;Lorg/springframework/http/HttpMethod;)Lorg/springframework/http/client/ClientHttpRequest;','Spring add Header in REST Client Template Client',1,false,'-','Java'),
(10,'HTTP end point','org.apache.http.impl.client.InternalHttpClient.doExecute(Lorg/apache/http/HttpHost;Lorg/apache/http/HttpRequest;Lorg/apache/http/protocol/HttpContext;)Lorg/apache/http/client/methods/CloseableHttpResponse;','Apache Internal HTTP Client',1,false,'-','Java'),
(11,'WS end point','org.glassfish.jersey.client.JerseyInvocation.invoke()Ljavax/ws/rs/core/Response;','Jersey Webservice Client',2,false,'-','Java'),
(12,'WS end point','com.sun.xml.messaging.saaj.client.p2p.HttpSOAPConnection.post(Ljavax/xml/soap/SOAPMessage;Ljava/net/URL;)Ljavax/xml/soap/SOAPMessage;','HTTP SOAP connection',2,false,'-','Java'),
(13,'WS end point','com.sun.xml.ws.transport.http.client.HttpClientTransport.<init>(Lcom/sun/xml/ws/api/message/Packet;Ljava/util/Map;)V','HTTP Client Transport',2,false,'-','Java'),
(14,'WS end point','com.sun.xml.ws.transport.http.client.HttpTransportPipe.processRequest(Lcom/sun/xml/ws/api/message/Packet;)Lcom/sun/xml/ws/api/pipe/NextAction;','HTTP Transport Pipe',2,false,'-','Java'),
(15,'WS end point','org.apache.cxf.jaxws.JaxWsClientProxy.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;','Apache cxf Webservice',2,false,'-','Java'),
(16,'RMI end point','java.rmi.Naming.lookup(Ljava/lang/String;)Ljava/rmi/Remote;','RMI Lookup Calls',5,false,'-','Java'),
(17,'RMI end point','java.rmi.Naming\$ParsedNamingURL.<init>(Ljava/lang/String;ILjava/lang/String;)','RMI Request',5,false,'-','Java'),
(19,'JDBC end point','oracle.jdbc.driver.OraclePreparedStatementWrapper','oracleDB',3,false,'-','Java'),
(20,'HADOOP end point','org.springframework.data.hadoop.hbase.HbaseTemplate.execute(Ljava/lang/String;Lorg/springframework/data/hadoop/hbase/TableCallback;)Ljava/lang/Object;','Spring HBASE',8,false,'-','Java'),
(21,'COHERENCE end point','com.tangosol.net.cache.CachingMap.get(Ljava/lang/Object;)Ljava/lang/Object;','Coherence get',4,false,'-','Java'),
(22,'COHERENCE end point','com.tangosol.net.cache.CachingMap.getAll(Ljava/util/Collection;)Ljava/util/Map;','Coherence getAll',4,false,'-','Java'),
(23,'COHERENCE end point','com.tangosol.net.cache.CachingMap.put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;','Coherence put',4,false,'-','Java'),
(24,'COHERENCE end point','com.tangosol.net.cache.CachingMap.put(Ljava/lang/Object;Ljava/lang/Object;ZJ)Ljava/lang/Object;','Coherence put',4,false,'-','Java'),
(25,'COHERENCE end point','com.tangosol.net.cache.CachingMap.putAll(Ljava/util/Map;)V','Coherence putAll',4,false,'-','Java'),
(26,'COHERENCE end point','com.tangosol.net.cache.CachingMap.remove(Ljava/lang/Object;)Ljava/lang/Object;','Coherence remove',4,false,'-','Java'),
(27,'MEM CACHE end point','net.rubyeye.xmemcached.XMemcachedClient.add0(Ljava/lang/String;ILjava/lang/Object;Lnet/rubyeye/xmemcached/transcoders/Transcoder;J)Z','Mem Cache add',6,false,'-','Java'),
(28,'MEM CACHE end point','net.rubyeye.xmemcached.XMemcachedClient.getMulti0(Ljava/util/Collection;JLnet/rubyeye/xmemcached/command/CommandType;Lnet/rubyeye/xmemcached/transcoders/Transcoder;)Ljava/util/Map;','MEM CACHE getMulti',6,false,'-','Java'),
(29,'MEM CACHE end point','net.rubyeye.xmemcached.XMemcachedClient.get0(Ljava/lang/String;JLnet/rubyeye/xmemcached/command/CommandType;Lnet/rubyeye/xmemcached/transcoders/Transcoder;)Ljava/lang/Object;','Mem Cache get',6,false,'-','Java'),
(30,'MEM CACHE end point','net.rubyeye.xmemcached.XMemcachedClient.delete0(Ljava/lang/String;IJZJ)Z','Mem Cache delete',6,false,'-','Java'),
(31,'MEM CACHE end point','net.rubyeye.xmemcached.XMemcachedClient.replace(Ljava/lang/String;ILjava/lang/Object;Lnet/rubyeye/xmemcached/transcoders/Transcoder;J)Z','Mem Cache replace',6,false,'-','Java'),
(32,'CLOUDANT end point','org.lightcouch.CouchDbClientBase.executeRequest(Lorg/apache/http/client/methods/HttpRequestBase;)Lorg/apache/http/HttpResponse;','Cloudant executeRequest',7,false,'-','Java'),
(33,'HTTP end point','javax.naming.ldap.InitialLdapContext.<init>(Ljava/util/Hashtable;[Ljavax/naming/ldap/Control;)V','Initial LDAP Context',1,false,'-','Java'),
(34,'HTTP end point','weblogic.servlet.internal.ServletResponseImpl.writeHeaders()V','Weblogic Servlet Response headers',1,false,'-','Java'),
(35,'HTTP end point','com.hazelcast.client.spi.ClientProxy.invoke(Lcom/hazelcast/client/impl/protocol/ClientMessage;)Ljava/lang/Object;','Hazelcast client proxy',1,false,'-','Java'),
(36,'JDBC end point','com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement','Prepared Statement : ibmDB',3,false,'-','Java'),
(37,'JDBC end point','com.ibm.ws.rsadapter.jdbc.WSJdbcStatement','Statement : ibmDB',3,false,'-','Java'),
(38,'JDBC end point','com.mysql.jdbc.PreparedStatement','Prepared Statement : mysqlDB',3,false,'-','Java'),
(39,'JDBC end point','org.apache.openjpa.kernel.DelegatingQuery.execute()Ljava/lang/Object;','execute()Ljava/lang/Object : openJPADB',3,false,'-','Java'),
(40,'JDBC end point','org.apache.openjpa.kernel.DelegatingQuery.execute(Ljava/util/Map;)Ljava/lang/Object;','execute(Ljava/util/Map;)Ljava/lang/Object : openJPADB',3,false,'-','Java'),
(41,'JDBC end point','org.apache.openjpa.kernel.DelegatingQuery.execute([Ljava/lang/Object;)Ljava/lang/Object;','execute([Ljava/lang/Object;)Ljava/lang/Object : openJPADB',3,false,'-','Java'),
(42,'REDIS end point','redis.clients.jedis.Jedis','Jedis : redisDB',10,false,'-','Java'),
(43,'REDIS end point','redis.clients.jedis.BinaryJedis','Binary Jedis : redisDB',10,false,'-','Java'),
(44,'MONGO end point','com.mongodb.DBCollection','DB Collection : mongoDB',11,false,'-','Java'),
(45,'MONGO end point','com.mongodb.DB',' DB : mongoDB',11,false,'-','Java'),
(46,'CASSANDRA end point','com.datastax.driver.core.SessionManager',' SessionManager : cassandraDB',12,false,'-','Java'),
(47,'CASSANDRA end point','com.datastax.driver.core.RequestHandler',' RequestHandler : cassandraDB',12,false,'-','Java'),
(48,'CUSTOM LOG end point','atg.nucleus.logging.LogEvent.<init>(Ljava/lang/String;Ljava/lang/Throwable;)V','LogEvent.<init>(String,Throwable)',13,false,'-','Java'),
(49,'CUSTOM LOG end point','atg.nucleus.logging.LogEvent.<init>(Ljava/lang/String;Ljava/lang/String;)V','LogEvent.<init>(String,String)',13,false,'-','Java'),
(50,'CUSTOM LOG end point','atg.nucleus.logging.LogEvent.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)V','LogEvent.<init>(String,String,Throwable)',13,false,'-','Java'),
(51,'CUSTOM LOG end point','atg.nucleus.logging.LogEvent.<init>(Ljava/lang/String;)V','LogEvent.<init>(String)',13,false,'-','Java'),
(52,'CUSTOM ERROR LOG end point','atg.nucleus.logging.LogEvent.<init>(Ljava/lang/String;Ljava/lang/Throwable;)V','LogEvent.<init>(String,Throwable)',14,false,'-','Java'),
(53,'CUSTOM ERROR LOG end point','atg.nucleus.logging.LogEvent.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)V','LogEvent.<init>(String,String,Throwable)',14,false,'-','Java'),
(54,'CUSTOM ERROR LOG end point','ch.qos.logback.classic.spi.LoggingEvent.<init>(Ljava/lang/String;Lch/qos/logback/classic/Logger;Lch/qos/logback/classic/Level;Ljava/lang/String;Ljava/lang/Throwable;[Ljava/lang/Object;)V','LoggingEvent.<init>(String,Logger,Level,String,Throwable,Object)',14,false,'-','Java'),
(55,'THREAD end point','java.lang.Thread.start()V','start()',15,false,'-','Java'),
(56,'THREAD end point','java.lang.Thread.run()V','run()',15,false,'-','Java'),
(57,'THREAD end point','java.util.concurrent.ThreadPoolExecutor.execute(Ljava/lang/Runnable;)V','execute(Runnable)',15,false,'-','Java'),
(58,'THREAD end point', 'java.util.concurrent.ThreadPoolExecutor.beforeExecute(Ljava/lang/Thread;Ljava/lang/Runnable;)V','beforeExecute(Thread,Runnable)',15, false,'-','Java'), 
(59,'THREAD end point','java.util.concurrent.ThreadPoolExecutor.afterExecute(Ljava/lang/Runnable;Ljava/lang/Throwable;)V','afterExecute(Throwable)',15,false,'-','Java'),
(60,'THREAD end point','java.util.concurrent.ForkJoinPool.addSubmission(Ljava/util/concurrent/ForkJoinTask;)V','addSubmission(ForkJoinTask)',15,false,'-','Java'),
(61,'THREAD end point','java.util.concurrent.ForkJoinTask.doExec()V','doExec()V',15,false,'-','Java'),
(62,'THREAD end point','java.util.concurrent.ForkJoinPool.externalPush(Ljava/util/concurrent/ForkJoinTask;)V','externalPush(ForkJoinTask)',15,false,'-','Java'),
(63,'THREAD end point','java.util.concurrent.ForkJoinTask.doExec()I','doExec()I',15,false,'-','Java'),
(64,'THREAD end point','com.tibco.pe.core.JobDispatcher.schedule(Lcom/tibco/pe/core/Job;)V','schedule(Job)',15,false,'-','Java'),
(65,'THREAD end point','com.tibco.pe.core.JobDispatcher$JobCourier.a(Lcom/tibco/pe/core/Job;)Z','a(Job)',15,false,'-','Java'),
(66,'WS end point','com.sun.xml.ws.transport.http.client.HttpTransportPipe.writeSOAPAction(Ljava/util/Map;Ljava/lang/String;Lcom/sun/xml/ws/api/message/Packet;)V','writeSOAPAction(Map,String,Packet)(i.e Ljava/lang/String;Lcom/sun/xml/ws/api/message/Packet;)',2,false,'-','Java'),
(67,'WS end point','com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest(Lcom/sun/xml/internal/ws/api/message/Packet;)Lcom/sun/xml/internal/ws/api/pipe/NextAction;','writeSOAPAction(Packet)',2,false,'-','Java'),
(68,'WS end point','com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.writeSOAPAction(Ljava/util/Map;Ljava/lang/String;)V','writeSOAPAction(Map,String)',2,false,'-','Java'),
(69,'WS end point','com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.writeSOAPAction(Ljava/util/Map;Ljava/lang/String;Lcom/sun/xml/internal/ws/api/message/Packet;)V','writeSOAPAction(Map,String,Packet)(i.e Lcom/sun/xml/internal/ws/api/message/Packet;)',2,false,'-','Java'),
(70,'HTTP end point for dot net','System.Net.HttpWebRequest.GetResponse','HttpWebRequest.GetResponse',16,false,'System.dll','Dot Net'),
(71,'HTTP end point for dot net','System.Net.HttpWebRequest.BeginGetRequestStream', 'HttpWebRequest.BeginGetRequestStream' ,18, false,'System.dll','Dot Net'),
(72,'HTTP end point for dot net','System.Net.HttpWebRequest.BeginGetResponse','HttpWebRequest.BeginGetResponse',16,false,'System.dll','Dot Net'),
(73,'HTTP end point for dot net','System.Net.HttpWebRequest.EndGetResponse','HttpWebRequest.EndGetResponse',16,false,'System.dll','Dot Net'),
(74,'HTTP end point for dot net','System.Net.HttpWebRequest.GetRequestStream','HttpWebRequest.GetRequestStream',18,false,'System.dll','Dot Net'),
(80,'SQL call for dot net','System.Data.SqlClient.SqlCommand.RunExecuteReader','SqlCommand.RunExecuteReader',17,false,'System.Data.dll','Dot Net'),
(82,'SQL call for dot net','System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery','SqlCommand.InternalExecuteNonQuery',17,false,'System.Data.dll','Dot Net'),
(83,'ASYNC call for dot net','System.Web.HttpApplication.ExecuteStep','HttpApplication.ExecuteStep',18,false,'System.Web.dll','Dot Net'),
(84,'ASYNC call for dot net','System.Runtime.IOThreadScheduler.ScheduleCallbackLowPriNoFlow','IOThreadScheduler.ScheduleCallbackLowPriNoFlow',18,false,'System.ServiceModel.Internals.dll','Dot Net'),
(85,'ASYNC call for dot net', 'System.ServiceModel.Activation.HostedHttpRequestAsyncResult.OnBeginRequest','HostedHttpRequestAsyncResult.OnBeginRequest',18, false,'System.ServiceModel.Activation.dll','Dot Net'),
(86,'CLOUDANT NoSQL end point','com.cloudant.client.org.lightcouch.CouchDatabaseBase.find(Ljava/lang/String;)Ljava/io/InputStream;','Cloudant NoSQL find',19,false,'-','Java'),
(87,'CLOUDANT NoSQL end point','com.cloudant.client.org.lightcouch.CouchDatabaseBase.save(Ljava/lang/Object;)Lcom/cloudant/client/org/lightcouch/Response;','Cloudant NoSQL save',19,false,'-','Java'),
(88,'CLOUDANT NoSQL end point','com.cloudant.client.org.lightcouch.CouchDatabaseBase.post(Ljava/lang/Object;)Lcom/cloudant/client/org/lightcouch/Response;','Cloudant NoSQL post',19,false,'-','Java'),
(89,'CLOUDANT NoSQL end point','com.cloudant.client.org.lightcouch.CouchDatabaseBase.update(Ljava/lang/Object;)Lcom/cloudant/client/org/lightcouch/Response;','Cloudant NoSQL update',19,false,'-','Java'),
(90,'CLOUDANT NoSQL end point','com.cloudant.client.org.lightcouch.CouchDatabaseBase.remove(Ljava/lang/Object;)Lcom/cloudant/client/org/lightcouch/Response;','Cloudant NoSQL remove',19,false,'-','Java'),
(91,'WS end point','com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection.post(Ljavax/xml/soap/SOAPMessage;Ljava/net/URL;)Ljavax/xml/soap/SOAPMessage;','post(SOAP,URL)',2,false,'-','Java'),
(92,'CASSANDRA end point','com.datastax.driver.core.AbstractSession',' AbstractSession : cassandraDB',12,false,'-','Java'),
(93,'CASSANDRA end point','com.datastax.driver.core.RequestHandler$SpeculativeExecution',' SpeculativeExecution : cassandraDB',12,false,'-','Java'),
(94,'HTTP end point','com.google.api.client.http.HttpRequest.execute()Lcom/google/api/client/http/HttpResponse;','Big Query',1,false,'-','Java'),
(95,'Big Table end point','com.google.cloud.bigtable.hbase.BigtableTable.put(Lorg/apache/hadoop/hbase/client/Put;)V','Big Table: Put',20,false,'-','Java'),
(96,'Big Table end point','com.google.cloud.bigtable.hbase.BigtableTable.get(Lorg/apache/hadoop/hbase/client/Get;)Lorg/apache/hadoop/hbase/client/Result;','Big Table: Get',20,false,'-','Java'),
(97,'Big Table end point','com.google.cloud.bigtable.hbase.BigtableTable.delete(Lorg/apache/hadoop/hbase/client/Delete;)V','Big Table: Delete',20,false,'-','Java'),
(98,'Microsoft SQL end point','com.microsoft.sqlserver.jdbc.SQLServerStatement','SQLServerStatement',21,false,'-','Java'),
(99,'Microsoft SQL end point','com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement','SQLServerPreparedStatement',21,false,'-','Java'),
(100,'HTTP end point','java.net.HttpURLConnection.setRequestMethod(Ljava/lang/String;)V','setRequestMethod(String)',1,false,'-','Java'),
(101,'HTTP end point','java.net.HttpURLConnection.getInputStream()Ljava/io/InputStream;','getInputStream()',1,false,'-','Java'),
(102,'HTTP end point','weblogic.net.http.HttpURLConnection.setRequestMethod(Ljava/lang/String;)V','setRequestMethod(String)',1,false,'-','Java'),
(103,'HTTP end point','weblogic.net.http.HttpURLConnection.getInputStream()Ljava/io/InputStream;','getInputStream()',1,false,'-','Java'),
(104,'HTTP end point','feign.Client$Default.execute(Lfeign/Request;Lfeign/Request$Options;)Lfeign/Response;','execute(Request,Request$Options)',1,false,'-','Java'),
(105,'HTTP end point','org.springframework.web.client.DefaultResponseErrorHandler.hasError(Lorg/springframework/http/client/ClientHttpResponse;)Z','hasError(ClientHttpResponse)',1,false,'-','Java'),
(106,'HTTP end point','java.net.URL.openConnection()Ljava/net/URLConnection;','openConnection()',1,false,'-','Java'),
(107,'HTTP end point','com.nds.nudetect.NuDetectClient.restCall(Ljava/lang/String;Ljava/lang/String;Lcom/nds/nudetect/ConstantsInternal$RESTRequestFunc;Lcom/nds/nudetect/TransactionParameters;)Lcom/nds/nudetect/RESTClientResponse;','restCall.<init>(String,String,ConstantsInternal$RESTRequestFunc,TransactionParameters)',1,false,'-','Java'),
(108,'HTTP end point','com.caucho.hessian.client.HessianProxy.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;','invoke(Object,Method,Object)',1,false,'-','Java'),
(109,'HTTP end point','com.caucho.hessian.client.HessianProxy.addRequestHeaders(Ljava/net/URLConnection;)V','addRequestHeaders(URLConnection)',1,false,'-','Java'),
(110,'HTTP end point','com.caucho.hessian.client.HessianProxy.sendRequest(Ljava/lang/String;[Ljava/lang/Object;)Lcom/caucho/hessian/client/HessianConnection;','sendRequest(String,Object)',1,false,'-','Java'),
(111,'THREAD end point','java.util.concurrent.ForkJoinPool.forkOrSubmit(Ljava/util/concurrent/ForkJoinTask;)V','forkOrSubmit(ForkJoinTask)',15,false,'-','Java'),
(112,'THREAD end point','java.util.concurrent.ForkJoinTask.fork()Ljava/util/concurrent/ForkJoinTask;','fork()',15,false,'-','Java'),
(113,'THREAD end point','java.util.concurrent.ForkJoinTask.doInvoke()I','doInvoke()',15,false,'-','Java'),
(114,'CUSTOM ERROR LOG end point','java.lang.Throwable.printStackTrace()V','printStackTrace()',14,false,'-','Java'),
(115,'CUSTOM ERROR LOG end point','java.lang.Throwable.printStackTrace(Ljava/io/PrintStream;)V','printStackTrace(PrintStream)',14,false,'-','Java'),
(116,'CUSTOM ERROR LOG end point','java.lang.Throwable.printEnclosedStackTrace(Ljava/lang/Throwable$PrintStreamOrWriter;[Ljava/lang/StackTraceElement;Ljava/lang/String;Ljava/lang/String;Ljava/util/Set;)V','printEnclosedStackTrace(PrintStreamOrWriter,StackTraceElement,String,String,Set)',14,false,'-','Java'),
(117,'CUSTOM ERROR LOG end point','java.lang.Throwable.printStackTrace(Ljava/lang/Throwable$PrintStreamOrWriter;)V','printStackTrace(PrintStreamOrWriter)',14,false,'-','Java'),
(118,'CUSTOM ERROR LOG end point','java.lang.Throwable.printStackTrace(Ljava/io/PrintWriter;)V','printStackTrace(PrintWriter)',14,false,'-','Java'),
(119,'JDBC end point','oracle.jdbc.driver.OraclePreparedStatement','OraclePreparedStatement',3,false,'-','Java'),
(120,'JDBC end point','oracle.jdbc.driver.OracleStatement','OracleStatement',3,false,'-','Java'),
(121,'JDBC end point','com.mysql.cj.jdbc.PreparedStatement','Prepared Statement : mysqlDB',3,false,'-','Java'),
(122,'HADOOP end point','org.apache.hadoop.hbase.client.HTable.get(Lorg/apache/hadoop/hbase/client/Get;)Lorg/apache/hadoop/hbase/client/Result;','get(Get)',8,false,'-','Java'),
(123,'HADOOP end point','org.apache.hadoop.hbase.client.HTable.get(Ljava/util/List;)[Lorg/apache/hadoop/hbase/client/Result;','get(List)',8,false,'-','Java'),
(124,'HADOOP end point','org.apache.hadoop.hbase.client.HTable.batchCallback(Ljava/util/List;[Ljava/lang/Object;Lorg/apache/hadoop/hbase/client/coprocessor/Batch$Callback;)V','batchCallback(List,Object,Batch$Callback)',8,false,'-','Java'),
(125,'HADOOP end point','org.apache.hadoop.hbase.client.HTable.delete(Lorg/apache/hadoop/hbase/client/Delete;)V','delete(Delete)',8,false,'-','Java'),
(126,'HADOOP end point','org.apache.hadoop.hbase.client.HTable.doPut(Lorg/apache/hadoop/hbase/client/Put;)V','doPut(Put)',8,false,'-','Java'),
(127,'HADOOP end point','org.apache.hadoop.hbase.client.HTable.checkAndPut([B[B[B[BLorg/apache/hadoop/hbase/client/Put;)Z','checkAndPut(Put)',8,false,'-','Java'),
(128,'HADOOP end point','org.apache.hadoop.hbase.client.HTable.checkAndDelete([B[B[B[BLorg/apache/hadoop/hbase/client/Delete;)Z','checkAndDelete(Delete)',8,false,'-','Java'),
(129,'MONGO end point','com.mongodb.Mongo','Mongo',11,false,'-','Java'),
(130,'CUSTOM LOG end point','org.apache.catalina.valves.AccessLogValve.log(Ljava/lang/String;)V','log(String)',13,false,'-','Java'),
(131,'CUSTOM LOG end point','org.apache.catalina.valves.AccessLogValve.log(Ljava/io/CharArrayWriter;)V','log(CharArrayWriter)',13,false,'-','Java'),
(132,'CUSTOM LOG end point','ch.qos.logback.core.encoder.LayoutWrappingEncoder.convertToBytes(Ljava/lang/String;)[B','convertToBytes(String)',13,false,'-','Java'),
(133,'CUSTOM LOG end point','weblogic.servlet.logging.FormatStringBuffer.getBytes()[B','getBytes()',13,false,'-','Java'),
(134,'RMI end point','java.rmi.Naming.<init>(Ljava/lang/String;ILjava/lang/String;)','Naming.<init>(String,String)',5,false,'-','Java'),
(135,'WS end point','com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(Lcom/sun/jersey/api/client/ClientRequest;)Lcom/sun/jersey/api/client/ClientResponse;','_invoke(ClientRequest)',2,false,'-','Java'),
(136,'WS end point','org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.getResponseCode()I','getResponseCode()',2,false,'-','Java'),
(137,'WS end point','org.apache.cxf.jaxrs.client.WebClient.prepareHeaders(Ljava/lang/Class;Ljava/lang/Object;)Ljavax/ws/rs/core/MultivaluedMap;','prepareHeaders(Class,Object)',2,false,'-','Java'),
(138,'WS end point','org.apache.cxf.jaxrs.client.WebClient.doInvoke(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/reflect/Type;)Ljavax/ws/rs/core/Response;','doInvoke(String,Object,Class,Type)',2,false,'-','Java'),
(139,'WS end point','org.apache.cxf.jaxrs.client.WebClient.doInvoke(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/reflect/Type;Ljava/lang/Class;Ljava/lang/reflect/Type;)Ljavax/ws/rs/core/Response;','doInvoke(String,Object,Type,Class,Type)',2,false,'-','Java'),
(140,'WS end point','org.apache.cxf.jaxrs.client.WebClient.doInvoke(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/reflect/Type;Ljava/lang/Class;Ljava/lang/reflect/Type;)Ljavax/ws/rs/core/Response;','doInvoke(String,Object,Class,Type,Class,Type)',2,false,'-','Java'),
(141,'Log end point','org.apache.log4j.AppenderSkeleton.doAppend(Lorg/apache/log4j/spi/LoggingEvent;)V','Log: doappend(LoggingEvent)',22,false,'-','Java'),
(142,'XATransaction end point','oracle.jdbc.xa.client.OracleXAResource','XATransaction: OracleXAResource',24,false,'-','Java'),
(143,'JDBC Connection end point','weblogic.jdbc.common.internal.RmiDataSource','DBConnection: RmiDataSource',3,false,'-','Java'),
(144,'JDBC Connection end point','java.sql.DriverManager','DBConnection: DriverManager',3,false,'-','Java'),
(145,'JDBC Connection end point','org.apache.commons.dbcp.BasicDataSource','DBConnection: BasicDataSource',3,false,'-','Java'),
(146,'Neo4j DB Callout end point','org.neo4j.jdbc.http.driver.CypherExecutor.executeQuery(Lorg/neo4j/jdbc/http/driver/Neo4jStatement;)Lorg/neo4j/jdbc/http/driver/Neo4jResponse;','CypherExecutor.executeQuery(Neo4jStatement)',26,false,'-','Java'),
(147,'Neo4j DB Callout end point','org.neo4j.jdbc.bolt.BoltPreparedStatement.executeQuery()Ljava/sql/ResultSet;','BoltPreparedStatement.executeQuery()',26,false,'-','Java'),
(148,'Exception end point','java.lang.Throwable.<init>()V','Exception: <init>()V',23,false,'-','Java'),
(149,'Exception end point','java.lang.Throwable.<init>(Ljava/lang/String;)V','Exception: <init>(Ljava/lang/String;)V',23,false,'-','Java'),
(150,'Exception end point','java.lang.Throwable.<init>(Ljava/lang/Throwable;)V','Exception: <init>(Throwable)V',23,false,'-','Java'),
(151,'Exception end point','java.lang.Throwable.<init>(Ljava/lang/String;Ljava/lang/Throwable;)V','Exception: <init>(String,Throwable)V',23,false,'-','Java'),
(152,'Custom Log end point','io.undertow.server.handlers.accesslog.DefaultAccessLogReceiver.logMessage(Ljava/lang/String;)V','DefaultAccessLogReceiver.logMessage(String)',13,false,'-','Java'),
(153,'JMS IBM Backend','com.ibm.mq.jms.MQMessageProducer.send(Ljavax/jms/Message;IIJ)V','MQMessageProducer.send(Message,IIJ)V',27,false,'-','Java'),
(154,'JMS IBM Backend','com.ibm.mq.jms.MQMessageProducer.send(Ljavax/jms/Message;)V','MQMessageProducer.send(Message)V',27,false,'-','Java'),
(155,'JMS IBM Backend','com.ibm.mq.jms.MQMessageProducer.send(Ljavax/jms/Destination;Ljavax/jms/Message;)V','MQMessageProducer.send(Destination,Message)V',27,false,'-','Java'),
(156,'JMS IBM Backend','com.ibm.mq.jms.MQMessageProducer.send(Ljavax/jms/Destination;Ljavax/jms/Message;IIJ)V','MQMessageProducer.send(Destination,Message,IIJ)V',27,false,'-','Java'),
(157,'JMS Active Backend','org.apache.activemq.ActiveMQMessageProducer.send(Ljavax/jms/Destination;Ljavax/jms/Message;IIJ)V','ActiveMQMessageProducer.send(Destination,Message,IIJ)V',27,false,'-','Java'),
(158,'JMS Active Backend','org.apache.activemq.ActiveMQMessageProducer.send(Ljavax/jms/Destination;Ljavax/jms/Message;IIJLorg/apache/activemq/AsyncCallback;)V','ActiveMQMessageProducer.send(Destination,Message,AsyncCallback)V',27,false,'-','Java'),
(159,'JMS Rabbit Backend','com.rabbitmq.client.impl.AMQChannel.transmit(Lcom/rabbitmq/client/Method;)V','AMQChannel.transmit(Method)V',27,false,'-','Java'),
(160,'JMS Rabbit Backend','com.rabbitmq.client.impl.AMQChannel.transmit(Lcom/rabbitmq/client/impl/AMQCommand;)V','AMQChannel.transmit(AMQCommand)V',27,false,'-','Java'),
(161,'JMS ATG Backend','atg.dms.local.TopicPublisherImpl.publish(Ljavax/jms/Topic;Ljavax/jms/Message;)V','TopicPublisherImpl.publish(Topic,Message)V',27,false,'-','Java'),
(162,'JMS TIBCO Backend','com.tibco.tibjms.TibjmsMessageProducer._publish(Ljavax/jms/Destination;Ljavax/jms/Message;ZIIJZLjavax/jms/CompletionListener;)Lcom/tibco/tibjms/TibjmsMessage;','TibjmsMessageProducer._publish(Destination,Message,CompletionListener)V',27,false,'-','Java'),
(163,'Async HTTP Backend','org.apache.http.impl.nio.client.FutureWrapper','client.FutureWrapper',1,false,'-','Java'),
(164,'Async HTTP Backend','org.apache.http.concurrent.BasicFuture.completed(Ljava/lang/Object;)Z','BasicFuture.completed(Object)Z',1,false,'-','Java'),
(165,'Async HTTP Backend','org.apache.http.concurrent.BasicFuture.failed(Ljava/lang/Exception;)Z','BasicFuture.failed(Exception)Z',1,false,'-','Java'),
(166,'Async HTTP Backend','org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(Lorg/apache/http/nio/protocol/HttpAsyncRequestProducer;Lorg/apache/http/nio/protocol/HttpAsyncResponseConsumer;Lorg/apache/http/protocol/HttpContext;Lorg/apache/http/concurrent/FutureCallback;)Ljava/util/concurrent/Future;','InternalHttpAsyncClient.execute(HttpAsyncRequestProducer,HttpAsyncResponseConsumer,HttpContext,FutureCallback)',1,false,'-','Java'),
(167,'HADOOP end point','org.apache.hadoop.hbase.client.HTable.finishSetup()V','HTable.finishSetup()V',8,false,'-','Java'),
(168,'HTTP end point','org.apache.commons.httpclient.HttpClient.executeMethod(Lorg/apache/commons/httpclient/HostConfiguration;Lorg/apache/commons/httpclient/HttpMethod;Lorg/apache/commons/httpclient/HttpState;)I','HttpClient.executeMethod(HostConfiguration,HttpMethod,HttpState)',1,false,'-','Java'),
(169,'SQL call for dot net','System.Data.OracleClient.OracleCommand.ExecuteReader','OracleCommand.ExecuteReader',17,false,'System.Data.OracleClient.dll','Dot Net'),
(170,'SQL call for dot net','System.Data.OracleClient.OracleCommand.ExecuteNonQueryInternal','OracleCommand.ExecuteNonQueryInternal',17,false,'System.Data.OracleClient.dll','Dot Net');

INSERT INTO config.naming_rule_profile_backendtype_asso(assoc_id,host ,port,prefix ,service_name,table_name,topic_name,url,databaseproduct_name,databaseproduct_version,driver_name,driver_Version,query,user_name,backend_type_id,profile_id) VALUES
(1,true,false,false,false,false,false,false,false,false,false,false,false,false,1,1),
(2,true,false,false,false,false,false,false,false,false,false,false,false,false,2,1),
(3,true,false,false,false,false,false,false,false,false,false,false,false,false,3,1),
(4,true,false,false,false,false,false,false,false,false,false,false,false,false,4,1),
(5,true,false,false,false,false,false,false,false,false,false,false,false,false,5,1),
(6,true,false,false,false,false,false,false,false,false,false,false,false,false,6,1),
(7,true,false,false,false,false,false,false,false,false,false,false,false,false,7,1),
(8,true,false,false,false,false,false,false,false,false,false,false,false,false,8,1),
(9,true,false,false,false,false,false,false,false,false,false,false,false,false,9,1),
(10,true,false,false,false,false,false,false,false,false,false,false,false,false,10,1),
(11,true,false,false,false,false,false,false,false,false,false,false,false,false,11,1),
(12,false,false,false,false,false,false,false,false,false,false,false,false,false,12,1),
(13,false,false,false,false,false,false,false,false,false,false,false,false,false,13,1),
(14,false,false,false,false,false,false,false,false,false,false,false,false,false,14,1),
(15,false,false,false,false,false,false,false,false,false,false,false,false,false,15,1),
(16,false,false,false,false,false,false,false,false,false,false,false,false,false,16,888888),
(17,false,false,false,false,false,false,false,false,false,false,false,false,false,17,888888),
(18,false,false,false,false,false,false,false,false,false,false,false,false,false,18,888888),
(19,true,false,false,false,false,false,false,false,false,false,false,false,false,19,1),
(20,true,false,false,false,false,false,false,false,false,false,false,false,false,20,1),
(21,true,false,false,false,false,false,false,false,false,false,false,false,false,21,1),
(22,true,false,false,false,false,false,false,false,false,false,false,false,false,22,1),
(23,true,false,false,false,false,false,false,false,false,false,false,false,false,23,1),
(24,true,false,false,false,false,false,false,false,false,false,false,false,false,24,1),
(26,true,true,false,false,false,false,true,false,false,false,false,false,false,26,1),
(27,true,true,false,false,false,false,false,false,false,false,false,true,false,27,1);


INSERT INTO config.profile_backend_point_asso(assoc_id,enabled,end_point_id,profile_id) VALUES
(1,true,1,1),
(2,true,2,1),
(3,true,3,1),
(4,true,4,1),
(5,true,5,1),
(6,true,6,1),
(7,true,7,1),
(8,true,8,1),
(9,true,9,1),
(10,true,10,1),
(11,true,11,1),
(12,true,12,1),
(13,false,13,1),
(14,true,14,1),
(15,true,15,1),
(16,false,16,1),
(17,false,17,1),
(19,true,19,1),
(20,true,20,1),
(21,true,21,1),
(22,true,22,1),
(23,true,23,1),
(24,true,24,1),
(25,true,25,1),
(26,true,26,1),
(27,true,27,1),
(28,true,28,1),
(29,true,29,1),
(30,true,30,1),
(31,true,31,1),
(32,true,32,1),
(33,false,33,1),
(34,true,34,1),
(35,false,35,1),
(36,true,36,1),
(37,true,37,1),
(38,true,38,1),
(39,false,39,1),
(40,false,40,1),
(41,false,41,1),
(42,true,42,1),
(43,true,43,1),
(44,true,44,1),
(45,true,45,1),
(46,false,46,1),
(47,false,47,1),
(48,false,48,1),
(49,false,49,1),
(50,false,50,1),
(51,false,51,1),
(52,true,52,1),
(53,true,53,1),
(54,false,54,1),
(55,true,55,1),
(56,true,56,1),
(57,true,57,1),
(58,true,58,1),
(59,true,59,1),
(60,true,60,1),
(61,true,61,1),
(62,true,62,1),
(63,true,63,1),
(64,true,64,1),
(65,true,65,1),
(66,true,66,1),
(67,false,67,1),
(68,false,68,1),
(69,false,69,1),
(70,true,70,888888),
(71,false,71,888888),
(72,true,72,888888),
(73,true,73,888888),
(74,true,74,888888),
(80,true,80,888888),
(82,true,82,888888),
(83,true,83,888888),
(84,true,84,888888),
(85,true,85,888888),
(86,true,86,1),
(87,true,87,1),
(88,true,88,1),
(89,true,89,1),
(90,true,90,1),
(91,true,91,1),
(92,true,92,1),
(93,true,93,1),
(94,true,94,1),
(95,true,95,1),
(96,true,96,1),
(97,true,97,1),
(98,true,98,1),
(99,true,99,1),
(100,false,100,1),
(101,false,101,1),
(102,false,102,1),
(103,false,103,1),
(104,true,104,1),
(105,false,105,1),
(106,false,106,1),
(107,true,107,1),
(108,true,108,1),
(109,true,109,1),
(110,true,110,1),
(111,false,111,1),
(112,false,112,1),
(113,false,113,1),
(114,true,114,1),
(115,false,115,1),
(116,false,116,1),
(117,false,117,1),
(118,false,118,1),
(119,false,119,1),
(120,false,120,1),
(121,false,121,1),
(122,true,122,1),
(123,true,123,1),
(124,false,124,1),
(125,false,125,1),
(126,false,126,1),
(127,false,127,1),
(128,false,128,1),
(129,true,129,1),
(130,true,130,1),
(131,true,131,1),
(132,true,132,1),
(133,true,133,1),
(134,false,134,1),
(135,true,135,1),
(136,false,136,1),
(137,false,137,1),
(138,false,138,1),
(139,false,139,1),
(140,false,140,1),
(141,true,141,1),
(142,true,142,1),
(143,true,143,1),
(144,true,144,1),
(145,true,145,1),
(146,true,146,1),
(147,true,147,1),
(148,true,148,1),
(149,true,149,1),
(150,true,150,1),
(151,true,151,1),
(152,false,152,1),
(153,true,153,1),
(154,true,154,1),
(155,true,155,1),
(156,true,156,1),
(157,true,157,1),
(158,true,158,1),
(159,true,159,1),
(160,true,160,1),
(161,true,161,1),
(162,false,162,1),
(163,true,163,1),
(164,true,164,1),
(165,true,165,1),
(166,true,166,1),
(167,false,167,1),
(168,false,168,1),
(169,true,169,888888),
(170,true,170,888888);


INSERT INTO config.headers_type(ht_id,header_type_name) VALUES
(1,'request'),
(2,'response'),
(3,'cookie');

INSERT INTO config.headers_meta_data(hmd_id,ht_id,header_name) VALUES
(1,1,'Accept-Charset'),
(2,1,'Accept-Datetime'),
(3,1,'Accept-Encoding'),
(4,1,'Accept-Language'),
(5,1,'Accept'),
(6,1,'Authorization'),
(7,1,'Cache-Control'),
(8,1,'Connection'),
(9,1,'Content-Length'),
(10,1,'Content-MD5'),
(11,1,'Content-Type'),
(12,1,'Cookie'),
(13,1,'DNT'),
(14,1,'Date'),
(15,1,'Expect'),
(16,1,'Front-End-Https'),
(17,1,'Host'),
(18,1,'If-Match'),
(19,1,'If-Modified-Since'),
(20,1,'If-None-Match'),
(21,1,'If-Range'),
(22,1,'If-Unmodified-Since'),
(23,1,'Max-Forwards'),
(24,1,'Origin'),
(25,1,'Pragma'),
(26,1,'Proxy-Authorization'),
(27,1,'If-Range'),
(28,1,'Proxy-Connection'),
(29,1,'Range'),
(30,1,'Referer'),
(31,1,'TE'),
(32,1,'Upgrade'),
(33,1,'User-Agent'),
(34,1,'Via'),
(35,1,'Warning'),
(36,1,'X-ATT-DeviceId'),
(37,1,'X-Forwarded-For'),
(38,1,'X-Forwarded-Proto'),
(39,1,'X-Requested-With'),
(40,1,'X-Wap-Profile'),
(41,2,'Accept-Ranges'),
(42,2,'Access-Control-Allow-Origin'),
(43,2,'Age'),
(44,2,'Allow'),
(45,2,'Cache-Control'),
(46,2,'Connection'),
(47,2,'Content-Disposition'),
(48,2,'Content-Encoding'),
(49,2,'Content-Language'),
(50,2,'Content-Length'),
(51,2,'Content-Location'),
(52,2,'Content-MD5'),
(53,2,'Content-Range'),
(54,2,'Content-Security-Policy'),
(55,2,'Content-Type'),
(56,2,'Date'),
(57,2,'ETag'),
(58,2,'Expires'),
(59,2,'Last-Modified'),
(60,2,'Link'),
(61,2,'Location'),
(62,2,'P3P'),
(63,2,'Pragma'),
(64,2,'Proxy-Authenticate'),
(65,2,'Refresh'),
(66,2,'Retry-After'),
(67,2,'Server'),
(68,2,'Set-Cookie'),
(69,2,'Status'),
(70,2,'Strict-Transport-Security'),
(71,2,'Trailer'),
(72,2,'Transfer-Encoding'),
(73,2,'Vary'),
(74,2,'Via'),
(75,2,'WWW-Authenticate'),
(76,2,'Warning'),
(77,2,'X-Content-Security-Policy'),
(78,2,'X-Content-Type-Options'),
(79,2,'X-Frame-Options'),
(80,2,'X-Powered-By'),
(81,2,'X-UA-Compatible'),
(82,2,'X-WebKit-CSP'),
(83,2,'X-XSS-Protection'),
(84,2,'Accept-Charset'),
(85,2,'Accept-Datetime'),
(86,2,'Accept-Encoding'),
(87,2,'Accept'),
(88,2,'Authorization'),
(89,2,'Cookie'),
(90,2,'DNT'),
(91,2,'Expect'),
(92,2,'Front-End-Https'),
(93,2,'Host'),
(94,2,'If-Match'),
(95,2,'If-Modified-Since'),
(96,2,'If-None-Match'),
(97,2,'If-Range'),
(98,2,'If-Unmodified-Since'),
(99,2,'Max-Forwards'),
(100,2,'Origin'),
(101,2,'Proxy-Authorization'),
(102,2,'Proxy-Connection'),
(103,2,'CavNDFPInstance'),
(104,2,'TE'),
(105,2,'Upgrade'),
(106,2,'User-Agent'),
(107,2,'X-ATT-DeviceId'),
(108,2,'X-Forwarded-For'),
(109,2,'X-Forwarded-Proto'),
(110,2,'X-Requested-With'),
(111,2,'X-Wap-Profile'),
(112,1,'CavNDFPInstance'),
(113,2,'Referer'),
(114,2,'Range');


INSERT INTO config.value_type(val_id,val_type) VALUES
(1,'String'),
(2,'Numeric'),
(3,'Others');


INSERT INTO config.conditional_operator(opt_id,val_id,operators) VALUES
(1,1,'='),
(2,1,'!='),
(3,1,'contains'),
(4,1,'!contains'),
(5,2,'='),
(6,2,'!='),
(7,2,'<'),
(8,2,'<='),
(9,2,'>'),
(10,2,'>='),
(11,3,'PRESENT'),
(12,3,'!PRESENT'),
(13,1,'PRESENT'),
(14,1,'!PRESENT'),
(15,2,'PRESENT'),
(16,2,'!PRESENT');

INSERT INTO config.bussiness_trans_global(bt_global_id, complete, dynamic_req_type, dynamic_req_value, http_method, request_header, request_param, segment_type, segment_uri,segment_value, slow_transaction, uri_type, very_slow_transaction, profile_id, slow_threshold, very_slow_threshold) VALUES
(1, false, false,'httpMethod', true, false, false, 'FromFirst', true, 2, 3000, 'segmentOfURI', 5000, 1, '10', '20'),
(2, false, false,'httpMethod', true, false, false, 'FromFirst', true, 2, 3000, 'segmentOfURI', 5000, 777777, '10', '20'),
(3, false, false,'httpMethod', true, false, false, 'FromFirst', true, 2, 3000, 'segmentOfURI', 5000, 888888, '10', '20');

INSERT INTO config.ndc_keywords(ndc_key_id, ndc_key_name, ndc_key_min, ndc_key_max, ndc_def_value,ndc_key_val,ndc_key_type) VALUES 
(1,'NDC_WAIT_TIME_AFTER_TEST_IS_OVER','','','30','30',''),
(2,'NDC_CONTROL_MSG_ACK_TIMEOUT','','','10','10',''),
(3,'NDC_CONTROL_THREAD_EPOLL_TIMEOUT','','','10',10,''),
(4,'NDC_CONTINUE_ON_CONTROL_CONNECTION_ERROR','','','2','2',''),
(5,'NDC_TIME_TO_SEND_HEART_BEAT_TO_BCI','','','300','300',''),
(6,'NDP_TR_RUNNING_STATUS_POLL_INTERVAL','','','500','500',''),
(7,'NDP_NEW_RAW_DATA_POLL_INTERVAL','','','500','500',''),
(8,'ENABLE_METHOD_TIMING_TABLE','','','1','1',''),
(9,'NDP_OMIT_NON_NS_FLOWPATHS','','','1','1',''),
(10,'NDP_EXCLUDE_FLOWPATHS_OUTSIDE_TESTIDX','','','1','1',''),
(11,'NDP_TRACE_LEVEL','0','4','1','1',''),
(12,'MAX_METHOD_CALL_STACK','1','10485760','128','128',''),
(13,'NDP_INIT_CONCURRENT_FLOWPATHS','8','10485760','512','512',''),
(14,'NDP_DELTA_CONCURRENT_FLOWPATHS','8','10485760','512','512',''),
(15,'NDP_MAX_BUFFERED_META_DATA_BUFSIZE','8','1048576','64','64',''),
(16,'NDP_MAX_BUFFERED_BCI_ARG_BUFSIZE','8','1048576','64','64',''),
(17,'NDP_MAX_BUFFERED_HTTP_HEADER_MD_BUFSIZE','8','1048576','8','8',''),
(18,'NDP_MAX_BUFFERED_HTTP_HEADER_BUFSIZE','8','1048576','64','64',''),
(19,'NDP_MAX_BUFFERED_EXCEPTION_DATA_BUFSIZE','8','1048576','64','64',''),
(20,'NDP_MAX_BUFFERED_FLOWPATH_BUFSIZE','8','1048576','512','512',''),
(21,'NDP_MAX_BUFFERED_APPLOG_BUFSIZE','8','1048576','512','512',''),
(22,'NDP_MAX_BUFFERED_METHOD_TIMING_TABLE_ENTRIES','8','1048576','1024','1024',''),
(23,'NDP_MAX_BUFFERED_MEM_ALLOC_BUFSIZE','8','1048576','16','16',''),
(24,'NDP_MAX_BUFFERED_SQL_TABLE_BUFSIZE','32','1048576','32','32',''),
(25,'NDP_MAX_BUFFERED_SQL_RECORD_TABLE_BUFSIZE','8','1048576','16','16',''),
(26,'NDP_DEBUG_LOGFILE_ROLLOVER_SIZE','1','102400','100','100',''),
(27,'NDP_FORCE_UPLOAD_TIMEOUT','1','2592000000','10','10',''),
(28,'NDP_SECS_TO_MARK_AN_FP_DEAD','0','43200','90','90',''),
(29,'NDP_SECS_TO_CLEAN_DEAD_FLOWPATHS','0','43200','10','10',''),
(30,'DB_UPLOAD_MODE','','','1','1',''),
(31,'NDP_FORCE_ADD_URC_FOR_NS_FPI_IN_MAPPING_RECORD','','','0','0',''),
(32,'NDP_MAX_ENTRY_EXIT_RECORDS_IN_AN_FP','0','10000000','110000','110000',''),
(33,'NDP_LOWER_PROCESS_PRIORITY_FLAG','','','0','0',''),
(34,'NDP_MAX_BUFFERED_JMS_BUFSIZE','8','1048576','32','32',''),
(35,'NDP_MAX_CONCURRENT_THREADS_IN_JVM','','','512','512',''),
(36,'NDP_METHOD_TIMING_CSV_FLUSH_INTERVAL_SECS','0','10000000','300','300',''),
(37,'NDP_DISABLE_DUMPING_CAPTURED_HTTP_BODY','0','1','0','0',''),
(38,'NDC_STOP_INSTRUMENTATION_RESPONSE_TIMEOUT','','','300000','300000',''),
(39,'NDC_ACCEPT_NEW_AND_CLOSE_CURRENT_DATA_CONNECTION','','','1','1',''),
(40,'NDC_DATA_THD_TERM_RETRY_COUNT','','','50','50',''),
(41,'NDC_DATA_THD_TERM_RETRY_INTERVAL_MSEC','','','200000','200000',''),
(42,'SND_RESP_TO_BCI_ON_DATA_CONN','','','0','0',''),
(43,'NDC_LOG_BCI_AGGREGATE_RAW_DATA','','','0','0',''),
(44,'NDP_SEQ_BLOB_IN_FILE_MIN_SIZE','1','2048','64','64',''),
(45,'NDP_SEQ_BLOB_COMPRESSION_BUFFER_INIT_SIZE','1','2048','1024','1024',''),
(46,'MAX_BUFFERED_SQB_BUFSIZE','8','1024000','8192','8192',''),
(47,'NDC_WAIT_TIME_TO_SEND_FORCE_STOP_COMP_SIG','','','60','60',''),
(48,'NDP_DUMP_URC','','','0','0',''),
(49,'NDP_META_DATA_RECOVERY_RETRY_TIMEOUT_IN_SEC','','','60','60',''),
(50,'NDP_SQL_START_NORM_ID','0','2000000000','0','0',''),
(51,'NDP_ENABLE_SQL_TIMING','','','1','1',''),
(52,'NDP_ENABLE_SQL_RECORD','','','0','0',''),
(53,'NDP_ENABLE_BCIARG','','','1','1',''),
(54,'NDDBU_CHUNK_SIZE','','','134217728','134217728',''),
(55,'NDDBU_IDLE_TIME','','','5','5',''),
(57,'NDP_FORCE_ADD_URC_FOR_MISSING_FP_MAPPING_RECORD','','','0','0',''),
(58,'NDP_FREE_FP_MIN_SQB_SIZE','','','32768','32768',''),
(59,'NDP_RAW_DATA_BUF_SIZE','','','262144','262144',''),
(60,'NDP_GENERATE_FP_SIGNATURES','','','0','0',''),
(61,'NDP_MIN_RESPTIME_TO_FILTER_L1_FP','','','0','0',''),
(62,'NDP_BINARY_FORMAT_FOR_METHOD_TIMING','','','1','1',''),
(63,'NDC_BCI_TIME_DIFF_THRESHOLD_IN_MS','','','0','0',''),
(64,'NDC_HS_ST_IN_FILE_MIN_SIZE','1','2000000000','64','64',''),
(65,'NDC_HS_ST_COMPRESSION_BUFFER_INIT_SIZE','1','2000000000','1024','1024',''),
(66,'ND_ENABLE_MONITOR_LOG','','','0','0',''),
(67,'NDP_MAX_ENTRY_EXIT_RECORDS_IN_AN_FP_EX2','','','1000000','1000000',''),
(68,'ENABLE_AUTO_SCALING','','','0','0',''),
(69,'NDC_MODIFY_TOPO_ENTRY','','','1','1',''),
(70,'NDC_DATA_THD_TERM_RETRY_INTERVAL_SEC','','','20','20',''),
(71,'NDP_DEBUG_LOGLEVEL','0','4','0','0',''),
(72,'NDC_REUSE_INSTANCE_ID_TIME_IN_MIN','','','0','0',''),
(73,'NDP_ENABLE_METADATA_RECOVERY','','','1','1',''),
(74,'NDP_ALLOW_REQ_DETAIL_BEFORE_SQB_BEGIN_REC','','','1','1',''),
(75,'NDC_LOG_BCI_AGGREGATE_RAW_DATA_EX','','','0','0',''),
(76,'NDC_BCI_RESPONSE_TIME_FOR_METADATA_IN_SECS','','','60','60',''),
(77,'ENABLE_FP_STAT_MONITOR','','','0','0',''),
(78,'SEND_ACTIVE_INSTANCE_REP','','','1','1',''),
(79,'NDC_MAX_CTRL_CON','','','400','400',''),
(80,'NDP_MAX_SQL_INDEX_FROM_BCI','','','4096','4096',''),
(81,'NDC_TRACING_LEVEL','','','1 50','1 50',''),
(83,'NDP_SEQ_BLOB_IN_FILE_FLAG','','','1 B 10000','1 B 10000',''),
(85,'NDC_HS_ST_IN_FILE_FLAG','','','1 B','1 B',''),
(86,'ND_ENABLE_CAPTURE_DB_TIMING','','','1 0 0 0','1 0 0 0',''),
(87,'NDC_THRESHOLD_TIME_TO_MARK_APP_INACTIVE','','','3600000 600000','3600000 600000',''),
(88,'NDDBU_TMP_FILE_PATH','','','/mnt/tmp','/mnt/tmp',''),
(89,'ND_FPI_MASK','','','NDEID:56:4;AppID:46:10;TS:8:38;SeqNo:0:8;','NDEID:56:4;AppID:46:10;TS:8:38;SeqNo:0:8;',''),
(90,'NDC_THRESHOLD_TO_MARK_DELETED','','','1 8h','1 8h',''),
(91,'NDP_DELETED_INSTANCE_CLEANUP_DELAY','0','','3D','3D',''),
(92,'SND_RESP_TO_BCI_ON_DATA_CONN','0','1','0','0',''),
(93,'SEND_NDCOLLECTOR_IP','0','1','1','1','NDC'),
(94,'AUTO_SCALE_BLOCKED_TIER','','','','','NDC'),
(95,'AUTO_SCALE_ALLOWD_TIER','','','','','NDC'),
(96,'NDP_EXTENDED_METADATA','0','1','0','0','NDP'),
(97,'NDP_MAX_BEGIN_SEQ_LEN','0','256','256','256','NDP'),
(98,'NDP_FREE_FP_MEM_ON_COMPLETION','0','1','0','0','NDP'),
(99,'NDP_MEMPOOL_SETTINGS','','','','','NDP'),
(100,'NDP_MONITORS','','','','','NDP'),
(101,'NDP_ENABLE_SQL_METADATA_RECOVERY','0','1','1','1','NDP'),
(102,'NDP_THRESHOLD_DIFF_BET_FP_AND_ENTRY_MTD_RESPTIME_SEC','','','900','900','NDP'),
(81,'NDC_TRACING_LEVEL','','','1 50','1 50',''),
(83,'NDP_SEQ_BLOB_IN_FILE_FLAG','','','1 B 10000','1 B 10000',''),
(85,'NDC_HS_ST_IN_FILE_FLAG','','','1 B','1 B',''),
(86,'ND_ENABLE_CAPTURE_DB_TIMING','','','1 0 0 0','1 0 0 0',''),
(87,'NDC_THRESHOLD_TIME_TO_MARK_APP_INACTIVE','','','3600000 600000','3600000 600000',''),
(88,'NDDBU_TMP_FILE_PATH','','','/mnt/tmp','/mnt/tmp',''),
(89,'ND_FPI_MASK','','','NDEID:56:4;AppID:46:10;TS:8:38;SeqNo:0:8;','NDEID:56:4;AppID:46:10;TS:8:38;SeqNo:0:8;',''),
(90,'NDC_THRESHOLD_TO_MARK_DELETED','','','1 8h','1 8h',''),
(91,'NDP_DELETED_INSTANCE_CLEANUP_DELAY','0','','3D','3D',''),
(92,'SND_RESP_TO_BCI_ON_DATA_CONN','0','1','0','0',''),
(93,'SEND_NDCOLLECTOR_IP','0','1','1','1','NDC'),
(94,'AUTO_SCALE_BLOCKED_TIER','','','','','NDC'),
(95,'AUTO_SCALE_ALLOWD_TIER','','','','','NDC'),
(96,'NDP_EXTENDED_METADATA','0','1','0','0','NDP'),
(97,'NDP_MAX_BEGIN_SEQ_LEN','0','256','256','256','NDP'),
(98,'NDP_FREE_FP_MEM_ON_COMPLETION','0','1','0','0','NDP'),
(99,'NDP_MEMPOOL_SETTINGS','','','','','NDP'),
(100,'NDP_MONITORS','','','','','NDP'),
(101,'NDP_ENABLE_SQL_METADATA_RECOVERY','0','1','1','1','NDP'),
(102,'NDP_THRESHOLD_DIFF_BET_FP_AND_ENTRY_MTD_RESPTIME_SEC','','','900','900','NDP'),
(103,'NDP_NUM_NONPREP_SQL_LOAD_AT_INIT','','','2500','2500','NDP'),
(104,'NDP_SQL_NONPREP_ROLLOVER_SIZE_MB','','','100','100','NDP'),
(105,'NDP_PERIODIC_SCANDIR_TIME','','','600','600','NDP'),
(106,'NDP_MON_LARGE_FLOWPATH_METHOD_COUNT','','','10000','10000','NDP');


INSERT INTO config.container_type(container_id,description,container_type,container_name) VALUES
(1,'Asynchronous Transaction Rules for Jetty application','Jetty','jetty'),
(2,'Asynchronous Transaction Rules for Tomcat application','Tomcat','tomcat'),
(3,'Asynchronous Transaction Rules for Weblogic application','Weblogic','weblogic');


INSERT INTO config.nd_asynchronous_rule(async_rule_id,fqm,container_id,rule_type,dump_mode) VALUES
(1,'org.eclipse.jetty.server.Request.startAsync()Ljavax/servlet/AsyncContext;',1,'start',0),
(2,'org.eclipse.jetty.server.Request.startAsync(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)Ljavax/servlet/AsyncContext;',1,'start',0),
(3,'org.eclipse.jetty.server.AsyncContextState.dispatch(Ljavax/servlet/ServletContext;Ljava/lang/String;)V',1,'dispatch',2),
(4,'org.eclipse.jetty.server.AsyncContextState.dispatch(Ljava/lang/String;)V',1,'dispatch',2),
(5,'org.eclipse.jetty.server.AsyncContextState.dispatch()V',1,'dispatch',2),
(6,'org.eclipse.jetty.server.AsyncContextState.complete()V',1,'complete',2),
(7,'weblogic.servlet.internal.ServletRequestImpl.startAsync(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;Z)Ljavax/servlet/AsyncContext;',3,'start',0),
(8,'weblogic.servlet.internal.ServletRequestImpl.startAsync()Ljavax/servlet/AsyncContext;',3,'start',0),
(9,'weblogic.servlet.internal.ServletRequestImpl.startAsync(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse)Ljavax/servlet/AsyncContext;',3,'start',0),
(10,'weblogic.servlet.internal.async.AsyncContextImpl.dispatch()V',3,'dispatch',2),
(11,'weblogic.servlet.internal.async.AsyncContextImpl.dispatch(Ljava/lang/String;)V',3,'dispatch',2),
(12,'weblogic.servlet.internal.async.AsyncContextImpl.dispatch(Ljavax/servlet/ServletContext;Ljava/lang/String;)V',3,'dispatch',2),
(13,'weblogic.servlet.internal.async.AsyncContextImpl.complete()V',3,'complete',2),
(14,'org.apache.catalina.connector.Request.startAsync()Ljavax/servlet/AsyncContext;',2,'start',0),
(15,'org.apache.catalina.connector.Request.startAsync(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)Ljavax/servlet/AsyncContext;',2,'start',0),
(16,'org.apache.catalina.core.AsyncContextImpl.dispatch(Ljavax/servlet/ServletContext;Ljava/lang/String;)V',2,'dispatch',2),
(17,'org.apache.catalina.core.AsyncContextImpl.dispatch(Ljava/lang/String;)V',2,'dispatch',2),
(18,'org.apache.catalina.core.AsyncContextImpl.dispatch()V',2,'dispatch',2),
(19,'org.apache.catalina.core.AsyncContextImpl.complete()V',2,'complete',2);

INSERT INTO config.profile_async_type_assoc(assoc_id,container_id,enabled,profile_id) VALUES
(1,1,true,1),
(2,2,true,1),
(3,3,true,1);
CREATE SEQUENCE config.hibernate_sequence START WITH 1 INCREMENT BY 1 NO CYCLE;

COMMIT;
+
